export const sourceSnapshot = "569ff6a1c400bd514ff79f5f1050a684dc3afde3";

export const visualSpecStatus = {
  scope: "internal-implementation-contract",
  publicRoutes: false,
  approvalTarget: "visual implementation, not the rewrite workspace",
};

export const requiredIconNames = [
  "user",
  "model",
  "runtime",
  "thread",
  "turn",
  "event",
  "item",
  "tool",
  "shell",
  "file",
  "patch",
  "approval",
  "hook",
  "sandbox",
  "network",
  "client",
  "cloud",
  "memory",
  "schema",
  "release",
  "ci",
  "error",
  "source",
  "policy",
  "mcp",
  "skill",
  "plugin",
  "connector",
  "trace",
  "state",
  "config",
  "auth",
];

export const requiredLocalizedSurfaceNames = [
  "component title",
  "concept summary",
  "reader question",
  "legend labels",
  "control labels",
  "state and edge labels",
  "source anatomy summaries",
  "comprehension prompts",
  "review checklist",
  "fallback text",
];

const githubBlob = `https://github.com/openai/codex/blob/${sourceSnapshot}/`;
const defaultLeakageNote =
  "Use public labels and architectural claims only; do not copy source bodies.";
const defaultLocalizationContract = {
  languages: ["en", "zh"],
  requiredSurfaces: requiredLocalizedSurfaceNames,
};

function anchor(
  role,
  path,
  line,
  architectureClaim,
  readerTakeaway,
  visualState,
  leakageNotes = defaultLeakageNote,
) {
  return {
    role,
    path,
    pinnedUrl: `${githubBlob}${path}#L${line}`,
    architectureClaim,
    readerTakeaway,
    visualState,
    leakageNotes,
  };
}

function check(
  question,
  expectedAnswer,
  visualState,
  sourceEvidence,
  misconceptionCaught,
) {
  return {
    question,
    expectedAnswer,
    visualState,
    sourceEvidence,
    misconceptionCaught,
  };
}

function sourceReference(anchor) {
  return `${anchor.path}${anchor.pinnedUrl.slice(anchor.pinnedUrl.indexOf("#L"))}`;
}

function record({
  id,
  number,
  slug,
  zhSlug,
  displayName,
  concept,
  component,
  readerQuestion,
  secondaryDiagrams,
  iconSet,
  sourceAnchors,
  fallback = "static-svg",
  motionPolicy = "step",
  requiredStatesOrEdges,
  invariants,
  misconceptionsCaught,
  comprehensionChecks,
  reviewQuestions,
  targetPhase,
}) {
  const chapterPath = number
    ? `codex-from-source/chapter-${String(number).padStart(2, "0")}`
    : "codex-from-source/epilogue";
  const zhChapterPath = number
    ? `zh/codex-from-source/chapter-${String(number).padStart(2, "0")}`
    : "zh/codex-from-source/epilogue";

  const checksWithSourceRefs = comprehensionChecks.map((item) => {
    const sourceEvidenceRefs = sourceAnchors
      .filter((sourceAnchor) => item.sourceEvidence.includes(sourceAnchor.path))
      .map(sourceReference);

    return {
      ...item,
      sourceEvidenceRefs,
    };
  });

  return {
    id,
    chapter: number ? String(number) : "Epilogue",
    route: slug ?? chapterPath,
    zhRoute: zhSlug ?? zhChapterPath,
    displayName,
    concept,
    primaryInteractive: {
      component,
      readerQuestion,
    },
    secondaryDiagrams,
    iconSet,
    localizationContract: defaultLocalizationContract,
    sourceAnchors,
    fallback,
    motionPolicy,
    requiredStatesOrEdges,
    invariants,
    misconceptionsCaught,
    comprehensionChecks: checksWithSourceRefs,
    reviewQuestions,
    targetPhase,
  };
}

export const chapterVisualSpecs = [
  record({
    id: "ch01-architectural-bet",
    number: 1,
    displayName: {
      en: "Architectural Bet",
      zh: "架构赌注",
    },
    concept: {
      en: "Codex as a bounded agent operating system.",
      zh: "Codex 是受边界约束的 agent 操作系统。",
    },
    component: "BoundedAgentOSMap",
    readerQuestion: {
      en: "Which layers turn model intent into governed work?",
      zh: "哪些层把模型意图变成受治理的工作？",
    },
    secondaryDiagrams: [
      "Protocol-to-session layer map",
      "Three histories comparison",
      "Authority boundary legend",
    ],
    iconSet: [
      "user",
      "model",
      "runtime",
      "thread",
      "event",
      "tool",
      "approval",
      "sandbox",
      "client",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "contract",
        "codex-rs/protocol/src/protocol.rs",
        125,
        "Submission, Op, Event, and EventMsg define the public runtime language.",
        "The architecture begins with a protocol vocabulary, not a UI widget.",
        "Protocol layer selected",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/session/mod.rs",
        366,
        "The session facade exposes queues, event flow, status, and shutdown.",
        "Runtime ownership is behind a small facade.",
        "Session layer selected",
      ),
      anchor(
        "persistence",
        "codex-rs/core/src/context_manager/history.rs",
        34,
        "ContextManager owns the model-visible conversation history separately from UI transcript text.",
        "Model-visible context is curated runtime state.",
        "Model-visible history lane selected",
      ),
      anchor(
        "persistence",
        "codex-rs/rollout-trace/src/model/mod.rs",
        54,
        "The reduced rollout trace graph keeps conversation, inference, tools, terminal operations, and raw payloads as structured replay output.",
        "Replayable history is a graph of facts, not a screen recording.",
        "Rollout record lane selected",
      ),
      anchor(
        "persistence",
        "codex-rs/state/src/runtime/threads.rs",
        398,
        "The state runtime lists threads from queryable SQLite projections with filters, ordering, and cursors.",
        "Queryable projections answer list and search questions without replaying the whole rollout.",
        "Queryable projection lane selected",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/tools/orchestrator.rs",
        149,
        "The tool orchestrator computes an approval requirement before execution.",
        "Tool requests pass through approval before becoming effects.",
        "Approval gate selected",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/tools/orchestrator.rs",
        218,
        "The first tool attempt selects a concrete sandbox strategy.",
        "Execution authority is mediated by sandbox selection.",
        "Sandbox gate selected",
      ),
    ],
    requiredStatesOrEdges: [
      "client intent to submission queue",
      "runtime work to event stream",
      "tool request to approval and sandbox before effect",
      "replaceable clients consuming the same events",
    ],
    invariants: [
      "The model-visible surface is not execution authority.",
      "Clients render runtime decisions; they do not own the agent loop.",
    ],
    misconceptionsCaught: [
      "Codex is only a chat UI wrapper.",
      "Tool schema visibility is the same thing as permission.",
    ],
    comprehensionChecks: [
      check(
        "If the TUI is replaced, which layer remains stable?",
        "The protocol and session facade: submissions enter and events leave.",
        "Client surface hidden",
        "Source anchors: codex-rs/protocol/src/protocol.rs; codex-rs/core/src/session/mod.rs",
        "The UI owns the runtime.",
      ),
      check(
        "Where should a shell side effect be visually blocked?",
        "At policy, approval, sandbox, or handler gates before execution.",
        "Tool path in blocked state",
        "Source anchors: codex-rs/core/src/tools/orchestrator.rs",
        "A tool call executes as soon as the model names it.",
      ),
    ],
    reviewQuestions: [
      "Can the reader identify every authority boundary without opening source?",
      "Does the map show failure and blocked paths, not only the happy path?",
    ],
    targetPhase: "P1 pilot",
  }),
  record({
    id: "ch02-startup-router",
    number: 2,
    displayName: {
      en: "Distribution to Router",
      zh: "从分发包装到 Rust 路由器",
    },
    concept: {
      en: "Startup narrows product intent before the runtime exists.",
      zh: "启动阶段在 runtime 存在前先收窄产品意图。",
    },
    component: "StartupRouteTimeline",
    readerQuestion: {
      en: "How does command intent narrow before runtime starts?",
      zh: "命令意图如何在 runtime 启动前被收窄？",
    },
    secondaryDiagrams: [
      "npm wrapper to native binary chain",
      "CLI command family matrix",
    ],
    iconSet: [
      "release",
      "runtime",
      "client",
      "shell",
      "config",
      "mcp",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "release",
        "codex-cli/bin/codex.js",
        175,
        "The JavaScript wrapper is delivery glue around the native entrypoint.",
        "Distribution can be product-critical without owning architecture.",
        "Wrapper stage active",
      ),
      anchor(
        "runtime",
        "codex-rs/cli/src/main.rs",
        106,
        "The Rust CLI routes commands before any agent session is started.",
        "The CLI is a router, not the agent loop.",
        "Router branch selected",
      ),
    ],
    requiredStatesOrEdges: [
      "package invocation to native binary",
      "argv and invocation name to command family",
      "interactive command to runtime startup",
      "app-server, login, MCP, and debug commands bypassing a turn",
    ],
    invariants: [
      "Startup is allowed to choose a product surface before session creation.",
      "Hidden commands are still contracts if users or integrations rely on them.",
    ],
    misconceptionsCaught: [
      "The npm wrapper is the architecture.",
      "Every CLI path starts an agent turn.",
    ],
    comprehensionChecks: [
      check(
        "Which branch starts the core runtime?",
        "The interactive or exec-like branch after CLI routing, not every command.",
        "Interactive branch highlighted",
        "Source anchors: codex-rs/cli/src/main.rs",
        "All commands are agent turns.",
      ),
      check(
        "What breaks if the wrapper owns feature decisions?",
        "Platform delivery would become entangled with runtime routing.",
        "Wrapper expanded with warning",
        "Source anchors: codex-cli/bin/codex.js; codex-rs/cli/src/main.rs",
        "Delivery code should own runtime policy.",
      ),
    ],
    reviewQuestions: [
      "Can the reader see where product intent stops and runtime begins?",
      "Does the timeline distinguish delivery glue from command routing?",
    ],
    targetPhase: "P2 foundations",
  }),
  record({
    id: "ch03-constraint-envelope",
    number: 3,
    displayName: {
      en: "Config, Auth, and Requirements",
      zh: "配置、认证与受管要求",
    },
    concept: {
      en: "Runtime behavior is compiled from preferences, credentials, and policy.",
      zh: "runtime 行为由偏好、凭据和策略共同编译出来。",
    },
    component: "ConstraintEnvelopeBuilder",
    readerQuestion: {
      en: "Which inputs become the final runtime envelope?",
      zh: "哪些输入会形成最终 runtime envelope？",
    },
    secondaryDiagrams: [
      "Config provenance stack",
      "Managed requirement decision tree",
    ],
    iconSet: [
      "config",
      "auth",
      "policy",
      "sandbox",
      "network",
      "runtime",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core/src/config/mod.rs",
        971,
        "The config layer stack produces an effective merged TOML before runtime config construction.",
        "Config is a compiled envelope, not a single file.",
        "Envelope assembled",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/config/permissions.rs",
        300,
        "Permission compilation turns profile choices into enforceable policy.",
        "Config can be part of safety.",
        "Permission layer toggled",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/config/managed_features.rs",
        25,
        "Managed feature gates can disable or require behaviors.",
        "Requirements can fail closed.",
        "Managed requirement active",
      ),
    ],
    requiredStatesOrEdges: [
      "defaults to user profile",
      "CLI override to turn-scoped context",
      "managed requirement overriding preference",
      "auth snapshot feeding runtime availability",
      "diagnostic path for disabled features",
    ],
    invariants: [
      "Managed requirements outrank user preference.",
      "Credentials are runtime inputs but must not leak into visual fixtures.",
    ],
    misconceptionsCaught: [
      "Configuration is just a TOML file.",
      "Authentication is unrelated to architecture.",
    ],
    comprehensionChecks: [
      check(
        "If a managed rule disables a feature, what should the visual show?",
        "The envelope rejects that capability before runtime use.",
        "Managed rule selected",
        "Source anchors: codex-rs/core/src/config/managed_features.rs",
        "User preference always wins.",
      ),
      check(
        "Where should credential state appear?",
        "As availability and trust state, never as secret text.",
        "Auth snapshot visible",
        "Source anchors: codex-rs/core/src/config/mod.rs; codex-rs/core/src/config/permissions.rs",
        "Auth can be rendered as raw credential material.",
      ),
    ],
    reviewQuestions: [
      "Can a reader predict which layer wins for a setting?",
      "Does the component avoid exposing secrets while teaching auth state?",
    ],
    targetPhase: "P2 foundations",
  }),
  record({
    id: "ch04-protocol-boundary",
    number: 4,
    displayName: {
      en: "Protocol Boundary",
      zh: "协议边界",
    },
    concept: {
      en: "Clients and runtime share a stable language of submissions, events, and schemas.",
      zh: "client 与 runtime 共享 submissions、events 和 schemas 组成的稳定语言。",
    },
    component: "SubmissionEventContractExplorer",
    readerQuestion: {
      en: "What is the stable language between clients and runtime?",
      zh: "client 和 runtime 之间的稳定语言是什么？",
    },
    secondaryDiagrams: [
      "Core protocol to app-server envelope",
      "Event-to-item mapping table",
      "Schema generation lane",
    ],
    iconSet: [
      "schema",
      "event",
      "item",
      "client",
      "runtime",
      "trace",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "contract",
        "codex-rs/protocol/src/protocol.rs",
        125,
        "Core submissions and events define the runtime contract.",
        "The core protocol is the canonical runtime vocabulary.",
        "Core contract selected",
      ),
      anchor(
        "contract",
        "codex-rs/app-server-protocol/src/jsonrpc_lite.rs",
        37,
        "The app-server wraps protocol behavior in a JSON-RPC envelope.",
        "Transport envelopes should not redefine runtime meaning.",
        "JSON-RPC envelope active",
      ),
      anchor(
        "generated-artifact",
        "codex-rs/app-server-protocol/src/export.rs",
        192,
        "Schema export turns contract surface into a governed artifact.",
        "Schemas are product APIs.",
        "Schema lane selected",
      ),
      anchor(
        "contract",
        "codex-rs/app-server-protocol/src/protocol/event_mapping.rs",
        30,
        "Event mapping preserves runtime meaning across the app-server boundary.",
        "Client items are projections of runtime events.",
        "Event mapping edge selected",
      ),
    ],
    requiredStatesOrEdges: [
      "submission to operation",
      "event to event message",
      "app request to core operation",
      "runtime event to app item",
      "schema generation from source contract",
    ],
    invariants: [
      "Compatibility paths are code paths, not comments.",
      "Transport normalization must preserve semantic identity.",
    ],
    misconceptionsCaught: [
      "JSON-RPC is the whole protocol.",
      "Generated schemas are secondary documentation.",
    ],
    comprehensionChecks: [
      check(
        "When a client sees an item update, where did the meaning originate?",
        "From the core runtime event, mapped into client-facing item form.",
        "Event-to-item edge highlighted",
        "Source anchors: codex-rs/app-server-protocol/src/protocol/event_mapping.rs",
        "The app-server invents runtime facts.",
      ),
      check(
        "Why should schema export be visible in the diagram?",
        "Because generated schemas are how the public contract is governed.",
        "Schema lane highlighted",
        "Source anchors: codex-rs/app-server-protocol/src/export.rs",
        "Schemas are only documentation.",
      ),
    ],
    reviewQuestions: [
      "Can the reader distinguish contract, envelope, and generated artifact?",
      "Does every mapping edge have a source-backed reason?",
    ],
    targetPhase: "P2 foundations",
  }),
  record({
    id: "ch05-durable-thread-ledger",
    number: 5,
    displayName: {
      en: "Threads, Sessions, and Durable State",
      zh: "线程、会话与持久状态",
    },
    concept: {
      en: "A turn becomes resumable because runtime, history, and storage stay separate.",
      zh: "turn 可恢复，是因为 runtime、history 与 storage 各自保持边界。",
    },
    component: "DurableThreadLedger",
    readerQuestion: {
      en: "How does a turn become resumable state?",
      zh: "一个 turn 如何变成可恢复状态？",
    },
    secondaryDiagrams: [
      "Thread/session/runtime stack",
      "Three histories ledger",
      "Resume/fork/rollback state diagram",
    ],
    iconSet: [
      "thread",
      "turn",
      "state",
      "memory",
      "event",
      "runtime",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "persistence",
        "codex-rs/core/src/thread_manager.rs",
        168,
        "Thread manager owns thread lifecycle and durable handles.",
        "Thread identity outlives one runtime session.",
        "Thread lane active",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/codex_thread.rs",
        98,
        "Client-facing thread handles connect durable thread state to session work.",
        "A handle is not the whole runtime.",
        "Thread handle selected",
      ),
      anchor(
        "persistence",
        "codex-rs/core/src/context_manager/history.rs",
        34,
        "Model-visible history is curated state, not raw UI scrollback.",
        "History has architectural ownership.",
        "History ledger selected",
      ),
    ],
    requiredStatesOrEdges: [
      "thread manager to thread handle",
      "thread handle to session facade",
      "accepted prompt to model-visible history",
      "resume and fork paths",
      "rollback altering persistent thread state",
    ],
    invariants: [
      "Runtime history, model history, and replay history are different ledgers.",
      "Accepted user input is recorded only after gates that can still reject it.",
    ],
    misconceptionsCaught: [
      "A thread is just a chat transcript.",
      "Resuming means replaying UI text.",
    ],
    comprehensionChecks: [
      check(
        "Which ledger should feed the next model request?",
        "The curated model-visible history, not raw terminal output.",
        "Model-history ledger selected",
        "Source anchors: codex-rs/core/src/context_manager/history.rs",
        "Scrollback is the model context.",
      ),
      check(
        "What survives when a session shuts down?",
        "Thread identity and durable state, not active runtime tasks.",
        "Session lane faded",
        "Source anchors: codex-rs/core/src/thread_manager.rs",
        "Session and thread lifetimes are identical.",
      ),
    ],
    reviewQuestions: [
      "Can the reader explain resume without source?",
      "Does the component visibly separate the three histories?",
    ],
    targetPhase: "P2 foundations",
  }),
  record({
    id: "ch06-turn-loop",
    number: 6,
    displayName: {
      en: "Turn Loop",
      zh: "Turn 循环",
    },
    concept: {
      en: "The agent emerges from a loop that gates, samples, dispatches, continues, and records.",
      zh: "agent 来自一个 gate、sample、dispatch、continue、record 的循环。",
    },
    component: "TurnLoopSimulator",
    readerQuestion: {
      en: "What repeats until the runtime decides to stop?",
      zh: "runtime 为什么以及如何持续循环？",
    },
    secondaryDiagrams: [
      "Turn state machine",
      "Hook ordering timeline",
      "Continuation and compaction branch map",
    ],
    iconSet: [
      "turn",
      "model",
      "hook",
      "tool",
      "event",
      "memory",
      "state",
      "error",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core/src/session/turn.rs",
        139,
        "The turn loop owns context preparation, sampling, tool work, continuation, and stop.",
        "The model call is one phase inside a larger state machine.",
        "Loop center active",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/session/turn.rs",
        313,
        "Prompt hooks run before the prompt becomes durable accepted history.",
        "A hook can block before the user prompt is recorded.",
        "Pre-record hook gate active",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/client.rs",
        232,
        "Model client sessions normalize streaming provider behavior for the loop.",
        "Provider streaming is behind a client session boundary.",
        "Model stream phase active",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "empty work rejection",
      "context preparation",
      "pre-prompt hooks",
      "accepted prompt recording",
      "model streaming normalization",
      "tool dispatch and pending input",
      "continuation decision",
      "compaction branch",
      "stop and after-agent hooks",
    ],
    invariants: [
      "A prompt is not durable until pre-submit gates allow it.",
      "Tool calls can cause another loop iteration instead of ending the turn.",
      "Compaction is part of control flow, not offline cleanup.",
    ],
    misconceptionsCaught: [
      "A turn is one model request.",
      "Hooks run only after the model has answered.",
      "Compaction is unrelated to runtime decisions.",
    ],
    comprehensionChecks: [
      check(
        "If a prompt hook blocks, what must disappear from later history?",
        "The blocked prompt should not be recorded as accepted conversation history.",
        "Pre-record hook blocks",
        "Source anchors: codex-rs/core/src/session/turn.rs",
        "Rejected input always enters history.",
      ),
      check(
        "Why can the loop continue after a tool call?",
        "Tool results can become model-visible output that requires another model step.",
        "Tool result feeds continuation",
        "Source anchors: codex-rs/core/src/session/turn.rs; codex-rs/core/src/client.rs",
        "Tool execution is the final phase.",
      ),
    ],
    reviewQuestions: [
      "Can the reader step through all loop branches without source?",
      "Does the simulator make hook ordering and recording order explicit?",
    ],
    targetPhase: "P1 pilot",
  }),
  record({
    id: "ch07-streaming-provider",
    number: 7,
    displayName: {
      en: "Model Providers",
      zh: "模型 Provider",
    },
    concept: {
      en: "Provider-specific streams are normalized before the runtime acts on them.",
      zh: "provider-specific streams 会先归一化，再被 runtime 使用。",
    },
    component: "StreamingProviderComparator",
    readerQuestion: {
      en: "How do different transports normalize into one stream?",
      zh: "不同 transport 如何归一成一个 stream？",
    },
    secondaryDiagrams: [
      "Provider prompt shape",
      "Retry and auth recovery branch",
      "Backend task contrast",
    ],
    iconSet: [
      "model",
      "network",
      "cloud",
      "event",
      "error",
      "auth",
      "runtime",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core/src/client.rs",
        215,
        "ModelClient owns provider communication at the runtime boundary.",
        "Provider details should not leak into turn logic.",
        "Provider client selected",
      ),
      anchor(
        "contract",
        "codex-rs/core/src/client_common.rs",
        28,
        "Prompt construction is the shared provider-facing shape.",
        "The runtime compiles one prompt contract before transport choice.",
        "Prompt shape inspected",
      ),
      anchor(
        "runtime",
        "codex-rs/cloud-tasks-client/src/api.rs",
        134,
        "The CloudBackend trait defines remote task operations as a backend contract.",
        "Remote task work should not be confused with provider streaming.",
        "Cloud contrast toggled",
      ),
    ],
    fallback: "table",
    motionPolicy: "scrubbable",
    requiredStatesOrEdges: [
      "prompt shape to provider request",
      "WebSocket stream to normalized events",
      "HTTPS fallback branch",
      "auth refresh branch",
      "retry budget exhaustion to structured error",
    ],
    invariants: [
      "Provider transport choice is below the turn loop contract.",
      "Retry is bounded and visible as state.",
    ],
    misconceptionsCaught: [
      "Each provider creates a different runtime.",
      "A stream error always ends the session fatally.",
    ],
    comprehensionChecks: [
      check(
        "Which output should the turn loop consume?",
        "Normalized provider events, not raw provider transport frames.",
        "Normalizer output selected",
        "Source anchors: codex-rs/core/src/client.rs",
        "The turn loop parses every provider directly.",
      ),
      check(
        "When does auth recovery belong in the visual?",
        "On provider boundary failures before emitting a final runtime error.",
        "Auth recovery branch active",
        "Source anchors: codex-rs/core/src/client.rs; codex-rs/core/src/client_common.rs",
        "Authentication errors are ordinary text output.",
      ),
    ],
    reviewQuestions: [
      "Can the reader compare transports without conflating them?",
      "Does failure handling have visible budgets and terminal states?",
    ],
    targetPhase: "P2 core",
  }),
  record({
    id: "ch08-rollout-trace",
    number: 8,
    displayName: {
      en: "Observability and Trace",
      zh: "可观测性与 Trace",
    },
    concept: {
      en: "Runtime facts become replayable history through a trace model and reducers.",
      zh: "runtime facts 通过 trace model 和 reducer 变成可回放历史。",
    },
    component: "RolloutTraceReplay",
    readerQuestion: {
      en: "How do runtime facts become replayable history?",
      zh: "runtime facts 如何变成可回放历史？",
    },
    secondaryDiagrams: [
      "Event payload to trace row",
      "Reducer state transition",
      "Replay timeline",
    ],
    iconSet: [
      "trace",
      "event",
      "state",
      "runtime",
      "item",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "persistence",
        "codex-rs/rollout-trace/src/model/session.rs",
        33,
        "Trace session models encode replayable runtime history.",
        "Trace is a structured model, not log text.",
        "Trace session selected",
      ),
      anchor(
        "runtime",
        "codex-rs/rollout-trace/src/protocol_event.rs",
        32,
        "Runtime protocol events are converted into trace payloads.",
        "Observed facts must preserve protocol meaning.",
        "Protocol event mapped",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/event_mapping.rs",
        135,
        "Core event mapping is the boundary between runtime events and rendered facts.",
        "Mapping is a source-owned architecture point.",
        "Event mapping selected",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "scrubbable",
    requiredStatesOrEdges: [
      "runtime event emitted",
      "protocol event normalized",
      "trace session row appended",
      "reducer updates replay state",
      "UI replay reconstructs visible history",
    ],
    invariants: [
      "Trace should explain event causality, not merely store logs.",
      "Replay state must be reconstructable from recorded facts.",
    ],
    misconceptionsCaught: [
      "Observability is only telemetry.",
      "Replay can be rebuilt from final messages alone.",
    ],
    comprehensionChecks: [
      check(
        "What does a trace replay need besides final text?",
        "Ordered protocol facts and reducer state transitions.",
        "Replay scrubber at intermediate event",
        "Source anchors: codex-rs/rollout-trace/src/model/session.rs",
        "Final transcript is enough for replay.",
      ),
      check(
        "Where should a malformed event be shown?",
        "At the mapping or reducer boundary with a structured error state.",
        "Mapping failure state",
        "Source anchors: codex-rs/rollout-trace/src/protocol_event.rs; codex-rs/core/src/event_mapping.rs",
        "Trace failures are invisible diagnostics.",
      ),
    ],
    reviewQuestions: [
      "Can the reader reconstruct why a visible item appeared?",
      "Does the replay show intermediate state, not only final output?",
    ],
    targetPhase: "P2 core",
  }),
  record({
    id: "ch09-tool-routing",
    number: 9,
    displayName: {
      en: "Tool Routing",
      zh: "工具路由",
    },
    concept: {
      en: "Model-visible tool specs become governed side effects through routing and orchestration.",
      zh: "模型可见工具 spec 通过 routing 和 orchestration 才变成受治理副作用。",
    },
    component: "ToolSpecToHandlerRouter",
    readerQuestion: {
      en: "Why is model-visible schema not execution authority?",
      zh: "为什么模型可见 schema 不是执行权限？",
    },
    secondaryDiagrams: [
      "Tool inventory classification",
      "Router to registry path",
      "Parallel dispatch safety lane",
    ],
    iconSet: [
      "model",
      "tool",
      "schema",
      "runtime",
      "approval",
      "sandbox",
      "event",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core/src/tools/spec_plan.rs",
        69,
        "Spec planning decides which tools are visible to the model.",
        "Visibility is planned before execution is possible.",
        "Spec plan selected",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/tools/router.rs",
        38,
        "The router converts model tool calls into typed invocations.",
        "Tool calls must cross a typed runtime boundary.",
        "Router edge active",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/tools/orchestrator.rs",
        57,
        "The orchestrator handles hooks, approvals, sandbox attempts, and events.",
        "Execution authority lives after routing, not in the schema.",
        "Orchestrator gate active",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "spec planning exposes tool",
      "model emits tool call",
      "router parses and classifies",
      "registry selects handler",
      "orchestrator applies hooks and approval",
      "events and model-visible result emitted",
    ],
    invariants: [
      "The model can name a tool but cannot skip runtime gates.",
      "Parallelism is an execution policy, not a schema feature.",
    ],
    misconceptionsCaught: [
      "Adding a schema means adding execution authority.",
      "Tool handlers are direct callbacks from the model.",
    ],
    comprehensionChecks: [
      check(
        "Where does a malformed tool argument fail?",
        "At router or handler parsing before side effects.",
        "Router parse failure",
        "Source anchors: codex-rs/core/src/tools/router.rs",
        "Bad arguments can still execute.",
      ),
      check(
        "Which layer asks for approval?",
        "The orchestrator path after routing and safety classification.",
        "Approval gate active",
        "Source anchors: codex-rs/core/src/tools/orchestrator.rs",
        "Approval is encoded only in the model schema.",
      ),
    ],
    reviewQuestions: [
      "Can a reader predict whether a tool call reaches execution?",
      "Does the visual keep schema, router, registry, and orchestrator separate?",
    ],
    targetPhase: "P1 pilot",
  }),
  record({
    id: "ch10-exec-backend",
    number: 10,
    displayName: {
      en: "Shell, Exec, and Filesystem",
      zh: "Shell、Exec 与文件系统",
    },
    concept: {
      en: "Shell and filesystem effects pass through handlers, policy, and backends.",
      zh: "shell 与文件系统副作用必须经过 handler、policy 和 backend。",
    },
    component: "ExecutionBackendPipeline",
    readerQuestion: {
      en: "Where are shell and filesystem effects authorized?",
      zh: "shell 和 filesystem effect 在哪里被授权？",
    },
    secondaryDiagrams: [
      "Shell versus unified exec taxonomy",
      "PTY lifecycle",
      "Filesystem backend boundary",
    ],
    iconSet: [
      "shell",
      "file",
      "runtime",
      "policy",
      "approval",
      "sandbox",
      "event",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core/src/tools/handlers/shell/shell_handler.rs",
        31,
        "The shell handler turns tool arguments into controlled command work.",
        "Shell execution is a handler path, not free-form process launch.",
        "Shell handler selected",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/tools/handlers/unified_exec/exec_command.rs",
        48,
        "Unified exec manages richer process sessions, stdin, PTY, and timeouts.",
        "Exec is a stateful tool surface.",
        "Unified exec selected",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/exec_policy.rs",
        272,
        "Exec policy determines approval and safety decisions.",
        "Authorization is a separate policy boundary.",
        "Exec policy active",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "tool call to shell or unified exec handler",
      "policy classification",
      "approval branch",
      "sandbox or backend execution",
      "stdout/stderr events",
      "long-lived stdin path",
    ],
    invariants: [
      "Process state and filesystem state must be rendered separately.",
      "Command output is evented and may be truncated without hiding lifecycle.",
    ],
    misconceptionsCaught: [
      "Shell execution is just a terminal subprocess.",
      "Filesystem work always happens locally.",
    ],
    comprehensionChecks: [
      check(
        "Where does a PTY session keep identity?",
        "In unified exec lifecycle state, not in a stateless shell string.",
        "PTY session expanded",
        "Source anchors: codex-rs/core/src/tools/handlers/unified_exec/exec_command.rs",
        "Every exec call is stateless.",
      ),
      check(
        "What decides whether a command needs approval?",
        "Exec policy and orchestration, before backend execution.",
        "Policy gate selected",
        "Source anchors: codex-rs/core/src/exec_policy.rs",
        "The command handler approves itself.",
      ),
    ],
    reviewQuestions: [
      "Can a reader distinguish shell, unified exec, and filesystem backend?",
      "Does the pipeline show authorization before effects?",
    ],
    targetPhase: "P2 core",
  }),
  record({
    id: "ch11-patch-workbench",
    number: 11,
    displayName: {
      en: "Patch Protocol",
      zh: "Patch 协议",
    },
    concept: {
      en: "Structured editing makes file mutation inspectable and governable.",
      zh: "结构化编辑让文件变更可检查、可治理。",
    },
    component: "PatchApplicationWorkbench",
    readerQuestion: {
      en: "How does structured editing avoid opaque shell mutation?",
      zh: "结构化编辑如何避免不透明 shell mutation？",
    },
    secondaryDiagrams: [
      "Patch grammar to runtime application",
      "Safety assessment branch",
      "Turn diff evidence panel",
    ],
    iconSet: [
      "patch",
      "file",
      "policy",
      "approval",
      "runtime",
      "event",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core/src/tools/handlers/apply_patch.rs",
        55,
        "The patch handler owns model-facing patch tool execution.",
        "Patches are first-class tool work.",
        "Patch handler active",
      ),
      anchor(
        "runtime",
        "codex-rs/apply-patch/src/parser.rs",
        126,
        "The parser enforces structured edit grammar before application.",
        "Syntax is a gate before file mutation.",
        "Grammar gate active",
      ),
      anchor(
        "persistence",
        "codex-rs/core/src/turn_diff_tracker.rs",
        18,
        "Turn diff tracking records evidence of file changes for clients.",
        "Diff evidence is part of runtime accountability.",
        "Diff tracker selected",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "patch text to grammar parse",
      "parse failure to model-visible error",
      "safety assessment",
      "approval branch",
      "filesystem application",
      "diff tracker update",
    ],
    invariants: [
      "Patch grammar success is not the same as authorization.",
      "Diff evidence must reflect attempted mutations.",
    ],
    misconceptionsCaught: [
      "Patch is a shell command wrapper.",
      "A syntactically valid patch is safe by definition.",
    ],
    comprehensionChecks: [
      check(
        "What happens before a patch touches the filesystem?",
        "Grammar parsing, runtime handling, safety, and approval gates.",
        "Pre-apply gates shown",
        "Source anchors: codex-rs/core/src/tools/handlers/apply_patch.rs; codex-rs/apply-patch/src/parser.rs",
        "Patch text directly mutates files.",
      ),
      check(
        "Why show the diff tracker?",
        "It is the evidence clients use to explain turn changes.",
        "Diff evidence panel open",
        "Source anchors: codex-rs/core/src/turn_diff_tracker.rs",
        "Patch output alone is enough accountability.",
      ),
    ],
    reviewQuestions: [
      "Can the reader see every gate before mutation?",
      "Does the workbench avoid copying real patch source code?",
    ],
    targetPhase: "P2 core",
  }),
  record({
    id: "ch12-human-gate-stack",
    number: 12,
    displayName: {
      en: "Hooks and Approval",
      zh: "Hooks 与人工审批",
    },
    concept: {
      en: "Human and automated gates can stop, amend, or explain work before effects land.",
      zh: "人工与自动 gate 可以在副作用落地前停止、修正或解释工作。",
    },
    component: "HumanGateStack",
    readerQuestion: {
      en: "Which gates can stop or amend a command?",
      zh: "哪些 gate 可以停止或修正命令？",
    },
    secondaryDiagrams: [
      "Hook event vocabulary",
      "Approval versus Guardian decision tree",
      "Headless interruption path",
    ],
    iconSet: [
      "hook",
      "approval",
      "policy",
      "user",
      "tool",
      "error",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "contract",
        "codex-rs/hooks/src/types.rs",
        92,
        "Hook event types describe the interception vocabulary.",
        "Hooks are typed extension points, not arbitrary callbacks.",
        "Hook event selected",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/hook_runtime.rs",
        321,
        "Prompt hook runtime executes gates before prompt acceptance.",
        "Some human/system decisions happen before model context changes.",
        "Prompt hook gate active",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/guardian/review.rs",
        234,
        "Guardian review is an automated decision path in the approval stack.",
        "Review is part of execution governance.",
        "Guardian branch active",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "hook discovery",
      "pre-prompt hook",
      "permission hook",
      "user approval",
      "Guardian review",
      "post-tool hook replacing output",
      "headless denial path",
    ],
    invariants: [
      "Hooks and approvals are related gates with different ownership.",
      "A gate can block work without becoming a model message.",
    ],
    misconceptionsCaught: [
      "Hooks only observe after execution.",
      "Approval is a UI popup rather than a runtime decision.",
    ],
    comprehensionChecks: [
      check(
        "Which gate can block before prompt recording?",
        "The prompt hook path.",
        "Prompt hook blocks",
        "Source anchors: codex-rs/core/src/hook_runtime.rs",
        "Hooks only run after model sampling.",
      ),
      check(
        "How is Guardian different from user approval?",
        "Guardian is an automated review path inside the gate stack.",
        "Guardian branch compared",
        "Source anchors: codex-rs/core/src/guardian/review.rs",
        "All approval decisions are human UI decisions.",
      ),
    ],
    reviewQuestions: [
      "Can the reader predict which gate owns each stop decision?",
      "Does the component show amend/replace paths, not only denial?",
    ],
    targetPhase: "P1 pilot",
  }),
  record({
    id: "ch13-containment-boundary",
    number: 13,
    displayName: {
      en: "Sandboxes and Network",
      zh: "沙箱与网络策略",
    },
    concept: {
      en: "Policy, transformation, and enforcement are different layers of containment.",
      zh: "policy、transform 和 enforcement 是不同层次的 containment。",
    },
    component: "ContainmentBoundaryExplorer",
    readerQuestion: {
      en: "What changes across platform sandboxes and network modes?",
      zh: "不同平台 sandbox 和 network mode 如何变化？",
    },
    secondaryDiagrams: [
      "Permission profile matrix",
      "Platform sandbox comparison",
      "Network proxy route map",
    ],
    iconSet: [
      "sandbox",
      "network",
      "policy",
      "shell",
      "file",
      "error",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "policy",
        "codex-rs/sandboxing/src/manager.rs",
        23,
        "Sandbox type selection chooses containment strategy before execution.",
        "Sandboxing is an explicit runtime choice.",
        "Sandbox type selected",
      ),
      anchor(
        "policy",
        "codex-rs/linux-sandbox/src/proxy_routing.rs",
        169,
        "Linux proxy routing shows network policy as its own route layer.",
        "Network control is not identical to process sandboxing.",
        "Network route active",
      ),
      anchor(
        "policy",
        "codex-rs/network-proxy/src/config.rs",
        271,
        "Network proxy config governs allowed and blocked network behavior.",
        "Network permission needs a visible decision path.",
        "Proxy policy inspected",
      ),
      anchor(
        "policy",
        "codex-rs/sandboxing/src/seatbelt.rs",
        602,
        "macOS Seatbelt enforcement is assembled as platform-specific command arguments.",
        "Platform backends are concrete enforcement paths.",
        "Seatbelt path selected",
      ),
      anchor(
        "policy",
        "codex-rs/windows-sandbox-rs/src/setup.rs",
        715,
        "Windows sandbox setup materializes a platform-specific filesystem handoff.",
        "Windows containment has its own setup path.",
        "Windows setup selected",
      ),
    ],
    fallback: "table",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "permission profile selection",
      "platform sandbox choice",
      "macOS Seatbelt path",
      "Linux helper and proxy path",
      "Windows identity/filesystem setup path",
      "network denied and approved branches",
    ],
    invariants: [
      "Sandbox policy is not enforcement unless the backend/platform enforces it.",
      "Network policy must be modeled separately from filesystem containment.",
    ],
    misconceptionsCaught: [
      "Sandbox means the same thing on every platform.",
      "Network approval is automatically a firewall.",
    ],
    comprehensionChecks: [
      check(
        "If sandbox selection falls back to none, what must the reader see?",
        "The containment edge weakens and the policy/enforcement distinction remains visible.",
        "Fallback sandbox state",
        "Source anchors: codex-rs/sandboxing/src/manager.rs",
        "Policy declaration always equals enforcement.",
      ),
      check(
        "Why is network shown as a separate plane?",
        "Network permission can be approved, proxied, or blocked independently.",
        "Network plane toggled",
        "Source anchors: codex-rs/linux-sandbox/src/proxy_routing.rs; codex-rs/network-proxy/src/config.rs",
        "Filesystem sandboxing fully explains network behavior.",
      ),
    ],
    reviewQuestions: [
      "Can the reader distinguish policy from enforcement?",
      "Does each platform path have an honest failure/fallback state?",
    ],
    targetPhase: "P2 core",
  }),
  record({
    id: "ch14-json-rpc-contract",
    number: 14,
    displayName: {
      en: "App-Server",
      zh: "App-Server",
    },
    concept: {
      en: "Multiple clients share runtime ownership through a JSON-RPC contract and thread state.",
      zh: "多个 client 通过 JSON-RPC contract 和 thread state 共享 runtime ownership。",
    },
    component: "JsonRpcContractMap",
    readerQuestion: {
      en: "How do clients share runtime ownership?",
      zh: "client 如何共享 runtime ownership？",
    },
    secondaryDiagrams: [
      "Transport normalization path",
      "Thread state and pending request board",
      "Notification mapping timeline",
    ],
    iconSet: [
      "client",
      "schema",
      "network",
      "thread",
      "event",
      "runtime",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "contract",
        "codex-rs/app-server-protocol/src/protocol/v2/turn.rs",
        49,
        "V2 turn-start parameters define a concrete app-server request surface.",
        "App-server API is a typed request contract, not ad hoc messages.",
        "Turn contract selected",
      ),
      anchor(
        "runtime",
        "codex-rs/app-server/src/message_processor.rs",
        275,
        "Message processing turns JSON-RPC requests into runtime work.",
        "Request processing is where client calls meet runtime ownership.",
        "Processor path active",
      ),
      anchor(
        "runtime",
        "codex-rs/app-server/src/request_serialization.rs",
        134,
        "Request serialization queues model exclusive and shared client work.",
        "Shared clients need explicit request ordering, not only validation.",
        "Serialization queue selected",
      ),
      anchor(
        "persistence",
        "codex-rs/app-server/src/thread_state.rs",
        70,
        "Thread state tracks pending requests and shared client-visible state.",
        "Shared clients need explicit state ownership.",
        "Thread state selected",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "transport receives envelope",
      "message processor validates request",
      "request serialized or rejected",
      "thread state updated",
      "runtime event mapped to notification",
      "client rejoin/replay path",
    ],
    invariants: [
      "Transport mode changes reachability, not runtime semantics.",
      "Pending client requests must be visible state.",
    ],
    misconceptionsCaught: [
      "App-server is just another UI.",
      "JSON-RPC envelopes own the agent loop.",
    ],
    comprehensionChecks: [
      check(
        "What persists if a client reconnects?",
        "Thread state and replayable notifications, not the disconnected socket.",
        "Rejoin path active",
        "Source anchors: codex-rs/app-server/src/thread_state.rs",
        "Connection lifetime equals thread lifetime.",
      ),
      check(
        "Where does a malformed JSON-RPC request stop?",
        "At envelope validation/request processing before runtime mutation.",
        "Request rejected",
        "Source anchors: codex-rs/app-server/src/request_serialization.rs; codex-rs/app-server/src/message_processor.rs",
        "Every app-server request becomes a runtime operation.",
      ),
    ],
    reviewQuestions: [
      "Can the reader explain shared ownership without source?",
      "Does transport normalization preserve contract meaning in the visual?",
    ],
    targetPhase: "P2 core",
  }),
  record({
    id: "ch15-client-reachability",
    number: 15,
    displayName: {
      en: "SDKs, Daemons, and Remote",
      zh: "SDK、Daemon 与远程控制",
    },
    concept: {
      en: "Different clients reach the same app-server contract through different transports.",
      zh: "不同 client 通过不同 transport 到达同一个 app-server contract。",
    },
    component: "ClientReachabilityMatrix",
    readerQuestion: {
      en: "How do SDKs and daemons reach the same contract?",
      zh: "SDK 和 daemon 如何到达同一个 contract？",
    },
    secondaryDiagrams: [
      "SDK facade comparison",
      "Daemon lifecycle timeline",
      "Transport reachability matrix",
    ],
    iconSet: [
      "client",
      "network",
      "cloud",
      "schema",
      "runtime",
      "auth",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/app-server-daemon/src/lib.rs",
        34,
        "Daemon lifecycle exposes long-lived app-server reachability.",
        "Daemonization is a deployment shape around the contract.",
        "Daemon lane active",
      ),
      anchor(
        "runtime",
        "codex-rs/app-server-transport/src/transport/mod.rs",
        57,
        "Transport modes normalize stdio, WebSocket, and related paths.",
        "Transport is a reachability choice.",
        "Transport matrix selected",
      ),
      anchor(
        "contract",
        "sdk/typescript/src/codex.ts",
        11,
        "The TypeScript SDK wraps the same contract for application code.",
        "SDKs are client facades over shared runtime semantics.",
        "SDK facade selected",
      ),
      anchor(
        "contract",
        "sdk/python/src/codex_app_server/api.py",
        72,
        "The Python SDK exposes the same app-server contract in Python form.",
        "Language bindings should preserve contract semantics.",
        "Python SDK facade selected",
      ),
    ],
    fallback: "table",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "SDK facade to transport",
      "daemon lifecycle states",
      "remote control branch",
      "transport failure state",
      "schema compatibility lane",
    ],
    invariants: [
      "SDK convenience must not redefine runtime semantics.",
      "Remote control is reachability, not a second architecture.",
    ],
    misconceptionsCaught: [
      "Each SDK owns different behavior.",
      "Daemon mode makes the app-server protocol irrelevant.",
    ],
    comprehensionChecks: [
      check(
        "What stays common across Python and TypeScript SDKs?",
        "The app-server contract and schema semantics.",
        "SDK rows compared",
        "Source anchors: sdk/python/src/codex_app_server/api.py; sdk/typescript/src/codex.ts",
        "SDK language changes runtime meaning.",
      ),
      check(
        "What does daemon mode add?",
        "Lifecycle and reachability around the same contract.",
        "Daemon lifecycle highlighted",
        "Source anchors: codex-rs/app-server-daemon/src/lib.rs",
        "Daemon mode is a separate agent runtime.",
      ),
    ],
    reviewQuestions: [
      "Can the matrix compare clients without duplicating explanations?",
      "Does it show failure and compatibility costs for each reachability path?",
    ],
    targetPhase: "P3 surfaces",
  }),
  record({
    id: "ch16-event-renderer",
    number: 16,
    displayName: {
      en: "TUI",
      zh: "终端 UI",
    },
    concept: {
      en: "The terminal UI is an event renderer, not the owner of agent decisions.",
      zh: "终端 UI 是事件渲染器，不是 agent 决策所有者。",
    },
    component: "EventRendererLab",
    readerQuestion: {
      en: "How does terminal UI project runtime events?",
      zh: "terminal UI 如何投影 runtime events？",
    },
    secondaryDiagrams: [
      "Four event sources",
      "Chat widget component tree",
      "Streaming markdown buffer timeline",
    ],
    iconSet: [
      "client",
      "event",
      "item",
      "runtime",
      "thread",
      "tool",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "ui",
        "codex-rs/tui/src/chatwidget.rs",
        658,
        "ChatWidget projects runtime and app events into terminal layout.",
        "The TUI renders event state rather than owning decisions.",
        "Chat widget selected",
      ),
      anchor(
        "ui",
        "codex-rs/tui/src/app_event.rs",
        133,
        "App events form the TUI's local event vocabulary.",
        "UI-local events are separate from runtime protocol events.",
        "App event lane selected",
      ),
      anchor(
        "tests",
        "codex-rs/tui/src/chatwidget/tests/exec_flow.rs",
        34,
        "Rendering tests pin user-visible exec flow behavior.",
        "UI behavior needs visual and source-backed tests.",
        "Exec rendering test selected",
      ),
    ],
    fallback: "static-svg",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "runtime event enters UI",
      "app event enters UI",
      "chat widget updates item",
      "bottom pane changes mode",
      "streaming markdown reflows",
      "approval popup interrupts input",
    ],
    invariants: [
      "UI state should not redefine runtime state.",
      "Streaming text needs stable buffers and reflow rules.",
    ],
    misconceptionsCaught: [
      "The terminal UI owns the turn loop.",
      "Rendering is a simple print of model text.",
    ],
    comprehensionChecks: [
      check(
        "What should happen when a command approval event arrives?",
        "The UI projects an approval surface while runtime waits on decision input.",
        "Approval popup state",
        "Source anchors: codex-rs/tui/src/app_event.rs; codex-rs/tui/src/chatwidget.rs",
        "The UI decides approval by itself.",
      ),
      check(
        "Why show streaming markdown as a buffer?",
        "Because rendering must handle deltas, stable text, and reflow separately.",
        "Streaming buffer expanded",
        "Source anchors: codex-rs/tui/src/chatwidget.rs; codex-rs/tui/src/chatwidget/tests/exec_flow.rs",
        "Streaming output is just appended final text.",
      ),
    ],
    reviewQuestions: [
      "Can the reader trace an event into terminal layout?",
      "Does the lab avoid making the UI look like the runtime owner?",
    ],
    targetPhase: "P1 pilot",
  }),
  record({
    id: "ch17-mcp-trust-plane",
    number: 17,
    displayName: {
      en: "MCP",
      zh: "MCP",
    },
    concept: {
      en: "MCP adds external tools through a separate trust and connection plane.",
      zh: "MCP 通过独立 trust 与 connection plane 增加外部工具。",
    },
    component: "ExternalToolTrustPlane",
    readerQuestion: {
      en: "How does MCP add tools without runtime entanglement?",
      zh: "MCP 如何在不缠住 runtime 的情况下增加工具？",
    },
    secondaryDiagrams: [
      "MCP transport comparison",
      "Tool exposure boundary",
      "OAuth and elicitation branch",
    ],
    iconSet: [
      "mcp",
      "connector",
      "tool",
      "auth",
      "network",
      "policy",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/codex-mcp/src/connection_manager.rs",
        72,
        "The connection manager owns MCP server connection lifecycle.",
        "External capability starts with connection ownership.",
        "Connection manager selected",
      ),
      anchor(
        "runtime",
        "codex-rs/codex-mcp/src/tools.rs",
        29,
        "MCP tool info describes external tools before core exposure.",
        "Tool metadata crosses a trust boundary.",
        "MCP tool info inspected",
      ),
      anchor(
        "policy",
        "codex-rs/core/src/mcp_tool_exposure.rs",
        18,
        "Core exposure decides which MCP tools enter the runtime surface.",
        "External tools are admitted, not merged into the core.",
        "Exposure boundary active",
      ),
    ],
    fallback: "static-svg",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "server config to connection manager",
      "transport startup",
      "tool listing snapshot",
      "allow/deny exposure",
      "elicitation or auth branch",
      "core tool surface admission",
    ],
    invariants: [
      "MCP extends capability without giving servers runtime ownership.",
      "Trust and transport are distinct visual planes.",
    ],
    misconceptionsCaught: [
      "MCP tools are core built-ins.",
      "A connected server means every tool is automatically exposed.",
    ],
    comprehensionChecks: [
      check(
        "What decides whether an MCP tool becomes model-visible?",
        "Core exposure policy after connection and metadata discovery.",
        "Exposure gate selected",
        "Source anchors: codex-rs/core/src/mcp_tool_exposure.rs",
        "Connection automatically grants tool visibility.",
      ),
      check(
        "Why show auth separately?",
        "OAuth or credential state affects reachability without changing core semantics.",
        "Auth branch active",
        "Source anchors: codex-rs/codex-mcp/src/connection_manager.rs; codex-rs/codex-mcp/src/tools.rs",
        "Auth is only a UI login detail.",
      ),
    ],
    reviewQuestions: [
      "Can the reader see where external trust enters?",
      "Does the component keep server, transport, and tool exposure separate?",
    ],
    targetPhase: "P3 extensions",
  }),
  record({
    id: "ch18-extension-provenance",
    number: 18,
    displayName: {
      en: "Skills and Plugins",
      zh: "Skills 与 Plugins",
    },
    concept: {
      en: "Extensions contribute capability with provenance, typed surfaces, and trust boundaries.",
      zh: "extension 带着 provenance、typed surface 和 trust boundary 贡献能力。",
    },
    component: "ExtensionProvenanceExplorer",
    readerQuestion: {
      en: "Which extension type contributes which capability?",
      zh: "不同 extension 类型贡献什么能力？",
    },
    secondaryDiagrams: [
      "Skill/plugin/connector comparison",
      "Manifest trust boundary",
      "Prompt contribution lane",
    ],
    iconSet: [
      "skill",
      "plugin",
      "connector",
      "mcp",
      "auth",
      "policy",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/core-skills/src/manager.rs",
        51,
        "SkillsManager owns skill discovery and loading.",
        "Skills are managed capability, not loose files.",
        "Skill lane selected",
      ),
      anchor(
        "contract",
        "codex-rs/core-plugins/src/manifest.rs",
        38,
        "Plugin manifests make plugin capabilities explicit.",
        "Plugin capability should be inspectable before use.",
        "Manifest inspected",
      ),
      anchor(
        "contract",
        "codex-rs/ext/extension-api/src/contributors/prompt.rs",
        12,
        "Prompt contributor APIs give extensions typed contribution points.",
        "Extensions should enter through typed surfaces.",
        "Prompt contributor selected",
      ),
      anchor(
        "contract",
        "codex-rs/connectors/src/lib.rs",
        66,
        "Connector directory entries model installable app capability.",
        "Connectors are a directory-backed capability type, not loose links.",
        "Connector directory selected",
      ),
    ],
    fallback: "table",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "skill discovery",
      "plugin manifest parse",
      "connector directory model",
      "typed prompt contribution",
      "trust/provenance tag",
      "capability exposed to runtime",
    ],
    invariants: [
      "Provenance must travel with extension-provided capability.",
      "Typed extension APIs prevent prompt or tool contribution from becoming invisible glue.",
    ],
    misconceptionsCaught: [
      "Skills, plugins, and connectors are the same mechanism.",
      "Extension text can enter context without ownership metadata.",
    ],
    comprehensionChecks: [
      check(
        "Which extension has manifest-backed capability?",
        "Plugins expose capability through manifest and manager paths.",
        "Plugin lane selected",
        "Source anchors: codex-rs/core-plugins/src/manifest.rs; codex-rs/core-skills/src/manager.rs",
        "All extension capability is discovered the same way.",
      ),
      check(
        "Why does provenance matter visually?",
        "Readers need to know which external source contributed context or capability.",
        "Provenance badge visible",
        "Source anchors: codex-rs/connectors/src/lib.rs; codex-rs/core-plugins/src/manifest.rs; codex-rs/ext/extension-api/src/contributors/prompt.rs",
        "Extension content is indistinguishable from core context.",
      ),
    ],
    reviewQuestions: [
      "Can a reader compare extension types without source?",
      "Does every contribution path show ownership and trust?",
    ],
    targetPhase: "P3 extensions",
  }),
  record({
    id: "ch19-compatibility-lanes",
    number: 19,
    displayName: {
      en: "Migration and Compatibility",
      zh: "迁移与兼容性",
    },
    concept: {
      en: "Compatibility is kept alive through explicit migration and protocol lanes.",
      zh: "兼容性通过显式 migration 和 protocol lane 被维持。",
    },
    component: "CompatibilityLaneBoard",
    readerQuestion: {
      en: "How are old and new surfaces kept alive together?",
      zh: "新旧 surface 如何并存？",
    },
    secondaryDiagrams: [
      "External config migration path",
      "Protocol compatibility lane",
      "Thread store continuity map",
    ],
    iconSet: [
      "config",
      "schema",
      "state",
      "thread",
      "client",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "contract",
        "codex-rs/app-server/src/config/external_agent_config.rs",
        105,
        "External agent config models old/new configuration surfaces.",
        "Migration needs typed source models.",
        "External config lane active",
      ),
      anchor(
        "runtime",
        "codex-rs/app-server/src/request_processors/external_agent_config_processor.rs",
        47,
        "Migration request processing makes compatibility executable.",
        "Compatibility is a code path.",
        "Migration processor selected",
      ),
      anchor(
        "persistence",
        "codex-rs/thread-store/src/store.rs",
        26,
        "ThreadStore defines the persistence boundary that protects user state during migration.",
        "Persistent state is the hardest compatibility boundary.",
        "Thread store lane selected",
      ),
    ],
    fallback: "table",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "legacy config detected",
      "migration processor executes",
      "new protocol surface receives equivalent state",
      "thread store remains readable",
      "deprecation warning branch",
    ],
    invariants: [
      "Backward compatibility must be visible as executable behavior.",
      "Stored thread state cannot be treated like disposable UI state.",
    ],
    misconceptionsCaught: [
      "Compatibility is only a changelog promise.",
      "Migration can be done only in docs.",
    ],
    comprehensionChecks: [
      check(
        "Where should a legacy config conversion be shown?",
        "Inside the migration processor lane, with output to the new surface.",
        "Migration lane active",
        "Source anchors: codex-rs/app-server/src/request_processors/external_agent_config_processor.rs",
        "Legacy config is handled by user instructions only.",
      ),
      check(
        "Which state is hardest to migrate safely?",
        "Durable thread store and persisted user state.",
        "Thread store highlighted",
        "Source anchors: codex-rs/thread-store/src/store.rs",
        "Only visible settings matter for compatibility.",
      ),
    ],
    reviewQuestions: [
      "Can the reader see old and new surfaces simultaneously?",
      "Does the board distinguish planned deprecation from broken compatibility?",
    ],
    targetPhase: "P3 advanced",
  }),
  record({
    id: "ch20-agent-graph",
    number: 20,
    displayName: {
      en: "Multi-Agent",
      zh: "多 Agent 协同",
    },
    concept: {
      en: "Child agents coordinate through graph, trace, and protocol edges without sharing internals.",
      zh: "child agents 通过 graph、trace 和 protocol edge 协同，但不共享内部过程。",
    },
    component: "AgentGraphOrchestrator",
    readerQuestion: {
      en: "How do child agents coordinate without sharing internals?",
      zh: "child agents 如何协同但不暴露内部过程？",
    },
    secondaryDiagrams: [
      "Agent graph edge status",
      "Spawn/wait/close lifecycle",
      "Trace reducer view of child work",
    ],
    iconSet: [
      "runtime",
      "thread",
      "cloud",
      "event",
      "trace",
      "state",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "persistence",
        "codex-rs/agent-graph-store/src/types.rs",
        7,
        "Graph edge status gives child-agent relationships durable shape.",
        "Coordination is represented as graph state.",
        "Graph edge selected",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/session/multi_agents.rs",
        16,
        "Session integration connects multi-agent actions to runtime coordination.",
        "Multi-agent behavior is part of session protocol.",
        "Session integration active",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/tools/handlers/multi_agents/spawn.rs",
        44,
        "The spawn-agent handler turns a model tool call into governed child-agent creation.",
        "Agent orchestration is concrete tool-governed work, not an implicit runtime side channel.",
        "Spawn handler lane selected",
      ),
      anchor(
        "runtime",
        "codex-rs/rollout-trace/src/reducer/tool/agents.rs",
        27,
        "Trace reducers model pending and observed child-agent edges.",
        "Child-agent orchestration must be replayable as graph evidence.",
        "Trace reducer lane selected",
      ),
    ],
    fallback: "static-svg",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "parent spawns child",
      "graph edge created",
      "message sent",
      "wait joins status",
      "close or resume branch",
      "trace records child events",
    ],
    invariants: [
      "Child agents coordinate by protocol and graph state, not shared memory.",
      "Waiting is an explicit operation with observable status.",
    ],
    misconceptionsCaught: [
      "Subagents are hidden function calls.",
      "Parent agents can inspect all child internals directly.",
    ],
    comprehensionChecks: [
      check(
        "What lets a parent wait on a child without sharing internals?",
        "Graph/protocol status and explicit wait operations.",
        "Wait edge highlighted",
        "Source anchors: codex-rs/agent-graph-store/src/types.rs; codex-rs/core/src/tools/handlers/multi_agents.rs",
        "Waiting requires shared mutable internals.",
      ),
      check(
        "Where should child-agent events appear in replay?",
        "In trace reducer views tied to graph/session events.",
        "Trace lane active",
        "Source anchors: codex-rs/rollout-trace/src/reducer/tool/agents.rs",
        "Child work is invisible to trace.",
      ),
    ],
    reviewQuestions: [
      "Can the reader predict fan-out and join behavior?",
      "Does the graph show ownership, status, and failure states?",
    ],
    targetPhase: "P1 pilot",
  }),
  record({
    id: "ch21-remote-task-contract",
    number: 21,
    displayName: {
      en: "Cloud Tasks",
      zh: "云任务",
    },
    concept: {
      en: "Remote work changes execution location while preserving local contract boundaries.",
      zh: "远程工作改变执行位置，但保留本地 contract 边界。",
    },
    component: "RemoteTaskContractTimeline",
    readerQuestion: {
      en: "What remains local when work moves remote?",
      zh: "工作转到远程后，哪些东西仍然必须留在本地？",
    },
    secondaryDiagrams: [
      "Task creation environment resolver",
      "Attempt lifecycle",
      "Local apply patch boundary",
    ],
    iconSet: [
      "cloud",
      "runtime",
      "auth",
      "thread",
      "patch",
      "state",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/cloud-tasks-client/src/api.rs",
        64,
        "TurnAttempt makes remote task attempts explicit units with status, diff, and messages.",
        "Remote work is observable as attempts, not one opaque final result.",
        "Attempt contract selected",
      ),
      anchor(
        "runtime",
        "codex-rs/agent-identity/src/lib.rs",
        40,
        "Agent identity material binds local runtime identity to remote work.",
        "Identity is part of the remote boundary.",
        "Identity lane active",
      ),
      anchor(
        "runtime",
        "codex-rs/cloud-tasks-client/src/http.rs",
        458,
        "Remote task apply returns a structured error when backend content is not a unified diff.",
        "Remote completion does not automatically become local mutation.",
        "Unified diff gate selected",
      ),
      anchor(
        "runtime",
        "codex-rs/cloud-tasks-client/src/http.rs",
        471,
        "Remote task apply crosses into local git patch application only through an explicit apply request.",
        "Local workspace mutation remains a separate boundary.",
        "Local apply boundary selected",
      ),
      anchor(
        "runtime",
        "codex-rs/cloud-tasks/src/lib.rs",
        641,
        "The cloud tasks UI starts preflight through the CloudBackend before apply.",
        "Preflight is an observable local acceptance step.",
        "Preflight call selected",
      ),
      anchor(
        "runtime",
        "codex-rs/cloud-tasks/src/lib.rs",
        702,
        "The cloud tasks UI starts apply through the CloudBackend as a distinct operation.",
        "Apply is not the same event as remote task completion.",
        "Apply call selected",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "task creation",
      "environment and branch resolution",
      "attempt starts",
      "remote execution runs",
      "local apply path",
      "identity and auth boundary",
      "failure and retry states",
    ],
    invariants: [
      "Remote execution does not remove local application and identity checks.",
      "Attempts are first-class lifecycle objects.",
    ],
    misconceptionsCaught: [
      "Cloud task means the local runtime disappears.",
      "Remote completion automatically mutates local files.",
    ],
    comprehensionChecks: [
      check(
        "What remains local after remote work completes?",
        "Apply/diff discipline and identity-aware acceptance boundaries.",
        "Local apply phase highlighted",
        "Source anchors: codex-rs/cloud-tasks-client/src/http.rs; codex-rs/cloud-tasks/src/lib.rs",
        "Remote success directly changes local workspace.",
      ),
      check(
        "Why are attempts visible?",
        "They are first-class units for retry, failure, and task progress.",
        "Attempt timeline selected",
        "Source anchors: codex-rs/cloud-tasks-client/src/api.rs",
        "A task has only one opaque final status.",
      ),
    ],
    reviewQuestions: [
      "Can the reader explain which contract moves remote and which stays local?",
      "Does identity appear as an architectural boundary?",
    ],
    targetPhase: "P3 advanced",
  }),
  record({
    id: "ch22-memory-side-channel",
    number: 22,
    displayName: {
      en: "Memories",
      zh: "Memories",
    },
    concept: {
      en: "Long-term context enters through constrained read and write side channels.",
      zh: "长期上下文通过受限制的 read/write side channels 进入。",
    },
    component: "MemorySideChannelExplorer",
    readerQuestion: {
      en: "How does long-term context enter without taking over?",
      zh: "长期上下文如何进入而不接管 runtime？",
    },
    secondaryDiagrams: [
      "Read-only memory service",
      "Citation evidence path",
      "Two-stage write consolidation",
    ],
    iconSet: [
      "memory",
      "mcp",
      "source",
      "trace",
      "state",
      "runtime",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/memories/read/src/usage.rs",
        8,
        "Memory usage kinds constrain how memories enter context.",
        "Memory reads are typed by usage, not free-form injection.",
        "Usage kind selected",
      ),
      anchor(
        "runtime",
        "codex-rs/memories/mcp/src/server.rs",
        86,
        "The memories MCP server registers list, read, and search tools only.",
        "Read-side memory access is intentionally narrower than memory writing.",
        "Read-only MCP service selected",
      ),
      anchor(
        "runtime",
        "codex-rs/memories/read/src/citations.rs",
        6,
        "Citation parsing connects remembered facts back to evidence.",
        "Memory needs evidence hooks.",
        "Citation lane active",
      ),
      anchor(
        "runtime",
        "codex-rs/memories/write/src/phase1.rs",
        70,
        "Stage 1 extraction begins a constrained write pipeline.",
        "Memory writing is staged, not immediate global mutation.",
        "Write phase 1 selected",
      ),
      anchor(
        "runtime",
        "codex-rs/memories/write/src/phase2.rs",
        45,
        "Stage 2 consolidation applies a separate controlled memory write phase.",
        "Global memory mutation requires a later consolidation boundary.",
        "Write phase 2 selected",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "read usage selected",
      "read-only MCP service returns context",
      "citation evidence attached",
      "phase 1 extracts per-rollout memory",
      "phase 2 consolidates global memory",
      "restricted internal agent boundary",
    ],
    invariants: [
      "Memory context must not silently override current runtime state.",
      "Write pipelines require evidence and staged consolidation.",
    ],
    misconceptionsCaught: [
      "Memory is just appended prompt text.",
      "A new memory instantly becomes global truth.",
    ],
    comprehensionChecks: [
      check(
        "Why do memory reads need citations?",
        "They let the reader and runtime connect context back to evidence.",
        "Citation badge selected",
        "Source anchors: codex-rs/memories/read/src/citations.rs",
        "Remembered context is self-authenticating.",
      ),
      check(
        "What prevents memory writes from taking over immediately?",
        "The staged extraction and consolidation pipeline.",
        "Two-stage write path active",
        "Source anchors: codex-rs/memories/write/src/phase1.rs; codex-rs/memories/write/src/phase2.rs",
        "Memory writes are direct global updates.",
      ),
    ],
    reviewQuestions: [
      "Can the reader distinguish read and write paths?",
      "Does the visual show memory as side channel, not core control plane?",
    ],
    targetPhase: "P3 advanced",
  }),
  record({
    id: "ch23-generated-contracts",
    number: 23,
    displayName: {
      en: "Build Systems",
      zh: "构建系统",
    },
    concept: {
      en: "Build overlays and generated schemas protect contracts as product artifacts.",
      zh: "build overlay 与生成 schema 把 contract 当作产品产物保护起来。",
    },
    component: "GeneratedContractDriftViewer",
    readerQuestion: {
      en: "Why are schemas treated as product artifacts?",
      zh: "为什么 schema 是产品产物？",
    },
    secondaryDiagrams: [
      "Cargo workspace ownership",
      "Bazel verification overlay",
      "Generated schema drift state machine",
    ],
    iconSet: [
      "schema",
      "ci",
      "release",
      "source",
      "config",
      "state",
    ],
    sourceAnchors: [
      anchor(
        "runtime",
        "codex-rs/Cargo.toml",
        118,
        "Workspace package metadata centralizes developer source ownership.",
        "Build architecture is visible through shared workspace metadata.",
        "Cargo workspace selected",
      ),
      anchor(
        "ci",
        ".github/workflows/bazel.yml",
        314,
        "Bazel verification checks release-build assumptions in CI.",
        "CI overlays can protect architecture without replacing local builds.",
        "Bazel lane active",
      ),
      anchor(
        "generated-artifact",
        "codex-rs/app-server-protocol/src/bin/export.rs",
        23,
        "Schema export creates generated contract artifacts.",
        "Generated schemas are versioned public product surface.",
        "Schema export selected",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "source contract changes",
      "schema generator runs",
      "generated artifact updates",
      "CI detects drift",
      "release verification consumes artifact",
    ],
    invariants: [
      "Generated contract drift is a product failure, not formatting noise.",
      "Bazel is an overlay for verification, not necessarily the sole developer path.",
    ],
    misconceptionsCaught: [
      "Generated schemas are documentation.",
      "Multiple build systems mean duplicated product architecture.",
    ],
    comprehensionChecks: [
      check(
        "What state should fail CI in the drift viewer?",
        "Source contract changed while generated schema output remains stale.",
        "Drift detected state",
        "Source anchors: codex-rs/app-server-protocol/src/bin/export.rs; .github/workflows/bazel.yml",
        "Generated output is optional.",
      ),
      check(
        "Why keep Cargo visible?",
        "It remains the developer source of truth even with CI overlays.",
        "Cargo lane selected",
        "Source anchors: codex-rs/Cargo.toml",
        "Bazel replaces all developer ownership.",
      ),
    ],
    reviewQuestions: [
      "Can the reader tell which artifact is generated and why it matters?",
      "Does the viewer show stale and regenerated states distinctly?",
    ],
    targetPhase: "P3 governance",
  }),
  record({
    id: "ch24-release-artifact",
    number: 24,
    displayName: {
      en: "Packaging and Release",
      zh: "打包与发布",
    },
    concept: {
      en: "Release turns source into native packages while preserving trust boundaries.",
      zh: "release 把源码变成 native package，同时保留 trust boundary。",
    },
    component: "ReleaseArtifactConveyor",
    readerQuestion: {
      en: "How does source become installable platform packages?",
      zh: "源码如何变成可安装的平台包？",
    },
    secondaryDiagrams: [
      "npm wrapper and native binary selector",
      "Release workflow artifact chain",
      "Native dependency quarantine",
    ],
    iconSet: [
      "release",
      "ci",
      "shell",
      "file",
      "network",
      "source",
      "error",
    ],
    sourceAnchors: [
      anchor(
        "release",
        "codex-cli/scripts/install_native_deps.py",
        47,
        "Native dependency installation maps deliverable binary components explicitly.",
        "Native binary selection is a delivery contract, not hidden npm metadata.",
        "Native component registry selected",
      ),
      anchor(
        "release",
        "codex-cli/scripts/build_npm_package.py",
        186,
        "Package builder copies native binaries into staged package output.",
        "Packaging is scripted product behavior.",
        "Package builder active",
      ),
      anchor(
        "release",
        "codex-cli/scripts/install_native_deps.py",
        37,
        "Native dependency installation treats platform binaries as explicit components.",
        "Native dependencies are a separate trust and delivery lane.",
        "Native dependency lane selected",
      ),
      anchor(
        "release",
        ".github/workflows/rust-release.yml",
        259,
        "Release workflow verifies native dependency artifact checksums.",
        "CI release jobs transfer source trust into installable artifacts.",
        "Checksum lane active",
      ),
      anchor(
        "release",
        ".github/workflows/rust-release.yml",
        300,
        "Release workflow signs Linux artifacts before packaging.",
        "Signing is an explicit release lane.",
        "Signing lane active",
      ),
      anchor(
        "release",
        ".github/workflows/rust-release.yml",
        380,
        "Release workflow copies built binaries into staged artifact output.",
        "CI release jobs transfer source trust into installable artifacts.",
        "Artifact staging lane active",
      ),
    ],
    fallback: "step-list",
    motionPolicy: "playable",
    requiredStatesOrEdges: [
      "source commit selected",
      "native binary built",
      "npm package staged",
      "native dependencies quarantined",
      "checksums/signing lane",
      "installer consumes artifact",
    ],
    invariants: [
      "Delivery architecture must not hide native dependency trust.",
      "Release artifacts should be traceable to source and workflow.",
    ],
    misconceptionsCaught: [
      "npm packaging is only metadata.",
      "Native dependency installation is outside architecture.",
    ],
    comprehensionChecks: [
      check(
        "Where does source trust transfer to users?",
        "Through release workflow, artifact staging, checksum/signing, and package metadata.",
        "Trust transfer lane selected",
        "Source anchors: .github/workflows/rust-release.yml",
        "Installing from npm hides all trust decisions.",
      ),
      check(
        "Why show native dependencies separately?",
        "They are quarantined delivery risks with platform behavior.",
        "Native dependency lane active",
        "Source anchors: codex-cli/scripts/install_native_deps.py",
        "Native dependencies are ordinary app files.",
      ),
    ],
    reviewQuestions: [
      "Can the reader trace source to installable package?",
      "Does the conveyor expose trust transfer and platform selection?",
    ],
    targetPhase: "P3 governance",
  }),
  record({
    id: "ch25-policy-lanes",
    number: 25,
    displayName: {
      en: "CI and Governance",
      zh: "CI 与治理",
    },
    concept: {
      en: "Governance checks preserve architecture by making violations fail loudly.",
      zh: "治理检查通过让违规显式失败来保护架构。",
    },
    component: "PolicyLaneDashboard",
    readerQuestion: {
      en: "Which checks preserve architecture over time?",
      zh: "哪些检查让架构不会随时间腐蚀？",
    },
    secondaryDiagrams: [
      "CI lanes by risk",
      "Boundary-check dependency map",
      "Generated drift state machine",
    ],
    iconSet: [
      "ci",
      "policy",
      "schema",
      "source",
      "error",
      "release",
    ],
    sourceAnchors: [
      anchor(
        "ci",
        ".github/workflows/rust-ci.yml",
        74,
        "Main CI workflow runs Cargo-native formatting checks as an executable PR lane.",
        "Governance starts with routine source checks.",
        "Main CI lane selected",
      ),
      anchor(
        "ci",
        ".github/scripts/verify_tui_core_boundary.py",
        18,
        "Boundary checks encode forbidden TUI-to-core source imports.",
        "Architecture boundaries need executable tests.",
        "Boundary check active",
      ),
      anchor(
        "ci",
        "scripts/check_blob_size.py",
        159,
        "Blob-size policy turns oversized non-allowlisted changed blobs into violations.",
        "Repository policy can defend reading and release costs.",
        "Blob-size lane selected",
      ),
    ],
    fallback: "table",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "source change enters CI",
      "risk lane selection",
      "boundary check passes or fails",
      "generated drift detected",
      "artifact-size policy blocks",
      "developer rework returns to source",
    ],
    invariants: [
      "Governance must match architectural risk, not only language boundaries.",
      "A failing exit code is a design decision when it protects a boundary.",
    ],
    misconceptionsCaught: [
      "CI is just correctness tests.",
      "Architecture governance lives in prose.",
    ],
    comprehensionChecks: [
      check(
        "Which failure protects the TUI/runtime boundary?",
        "The boundary verification script lane.",
        "Boundary lane fails",
        "Source anchors: .github/scripts/verify_tui_core_boundary.py",
        "Code review memory is enough to protect boundaries.",
      ),
      check(
        "Why should blob size be in an architecture dashboard?",
        "Asset growth affects release and reading performance, so policy protects product shape.",
        "Blob-size lane selected",
        "Source anchors: scripts/check_blob_size.py",
        "Size policy is unrelated housekeeping.",
      ),
    ],
    reviewQuestions: [
      "Can the reader map each CI lane to an architectural risk?",
      "Does the dashboard show both pass and fail consequences?",
    ],
    targetPhase: "P3 governance",
  }),
  record({
    id: "epilogue-transfer-atlas",
    number: null,
    displayName: {
      en: "Transfer Pattern Atlas",
      zh: "可迁移模式图谱",
    },
    concept: {
      en: "The book's visual patterns become reusable architecture tools.",
      zh: "本书的视觉模式变成可复用的架构工具。",
    },
    component: "TransferPatternAtlas",
    readerQuestion: {
      en: "Which visual patterns can readers reuse?",
      zh: "读者可以复用哪些视觉化架构模式？",
    },
    secondaryDiagrams: [
      "Pattern-to-chapter matrix",
      "Bounded runtime synthesis map",
      "Road-not-taken comparison",
    ],
    iconSet: [
      "runtime",
      "schema",
      "tool",
      "policy",
      "state",
      "trace",
      "source",
    ],
    sourceAnchors: [
      anchor(
        "contract",
        "codex-rs/protocol/src/protocol.rs",
        125,
        "The protocol family supplies the transferable contract pattern.",
        "Stable contracts are reusable architecture tools.",
        "Contract pattern selected",
      ),
      anchor(
        "runtime",
        "codex-rs/core/src/session/mod.rs",
        366,
        "The session runtime supplies the bounded loop pattern.",
        "Loops need gates, history, and event contracts.",
        "Runtime pattern selected",
      ),
      anchor(
        "ci",
        ".github/workflows/rust-ci.yml",
        74,
        "Governance workflows show architecture as executable policy.",
        "Architectural lessons must include maintenance mechanisms.",
        "Governance pattern selected",
      ),
    ],
    fallback: "table",
    motionPolicy: "step",
    requiredStatesOrEdges: [
      "contract pattern",
      "bounded loop pattern",
      "governed side-effect pattern",
      "traceable state pattern",
      "executable governance pattern",
    ],
    invariants: [
      "Transferable patterns must be abstract enough to reuse and concrete enough to act on.",
      "The final synthesis should not introduce new source claims.",
    ],
    misconceptionsCaught: [
      "The book's lessons are Codex-specific trivia.",
      "Patterns can be copied without their trade-offs.",
    ],
    comprehensionChecks: [
      check(
        "Which pattern should a reader reuse for tool safety?",
        "Governed side effects: spec, router, handler, gates, events, and evidence.",
        "Tool safety pattern selected",
        "Source anchors: codex-rs/protocol/src/protocol.rs; codex-rs/core/src/session/mod.rs",
        "Tool safety is only permission prompts.",
      ),
      check(
        "What makes the bounded runtime pattern reusable?",
        "A stable contract, explicit state, gated effects, and replayable events.",
        "Bounded runtime pattern selected",
        "Source anchors: codex-rs/core/src/session/mod.rs; .github/workflows/rust-ci.yml",
        "The pattern is just an LLM loop.",
      ),
    ],
    reviewQuestions: [
      "Can the reader leave with reusable architecture patterns?",
      "Does the atlas synthesize instead of re-listing chapters?",
    ],
    targetPhase: "P4 synthesis",
  }),
];
