// Generated by scripts/sync-leetcode-statement-assets.mjs.
// Do not edit by hand.

export interface LeetcodeProblemStatementAsset {
  type: "image" | "table";
  source: "leetcode-cn";
  html: string;
}

export const leetcodeProblemStatementAssets = {
  "trapping-rain-water": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/10/22/rainwatertrap.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 161px; width: 412px\" />"
    }
  ],
  "add-two-numbers": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2021/01/02/addtwonumber1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 483px; height: 342px\" />"
    }
  ],
  "merge-two-sorted-lists": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/03/merge_ex1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 662px; height: 302px\" />"
    }
  ],
  "spiral-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/spiral1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 242px; height: 242px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/spiral.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 242px\" />"
    }
  ],
  "reverse-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/rev1ex1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 542px; height: 222px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/rev1ex2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 182px; height: 222px\" />"
    }
  ],
  "reverse-nodes-in-k-group": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/03/reverse_ex1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 542px; height: 222px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/03/reverse_ex2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 542px; height: 222px\" />"
    }
  ],
  "lowest-common-ancestor-of-a-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2018/12/14/binarytree.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px; height: 190px\" />"
    }
  ],
  "spiral-matrix-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/spiraln.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 242px; height: 242px\" />"
    }
  ],
  "intersection-of-two-linked-lists": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/14/160_statement.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 130px; width: 400px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/05/160_example_1_1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 130px; width: 400px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/05/160_example_2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 136px; width: 350px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/14/160_example_3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 126px; width: 200px\" />"
    }
  ],
  "n-queens": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/queens.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 600px; height: 268px\" />"
    }
  ],
  "binary-tree-maximum-path-sum": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/13/exx1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 182px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/13/exx2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "search-a-2d-matrix-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/11/25/searchgrid2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/11/25/searchgrid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "palindrome-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/03/pal1linked-list.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 422px; height: 62px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/03/pal2linked-list.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 182px; height: 62px\" />"
    }
  ],
  "swap-nodes-in-pairs": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/03/swap_ex1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 422px; height: 222px\" />"
    }
  ],
  "construct-binary-tree-from-preorder-and-inorder-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 302px; width: 277px\" />"
    }
  ],
  "sort-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/14/sort_list_1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/14/sort_list_2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 550px\" />"
    }
  ],
  "minimum-path-sum": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/05/minpath.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 242px; height: 242px\" />"
    }
  ],
  "letter-combinations-of-a-phone-number": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1752723054-mfIHZs-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px\" />"
    }
  ],
  "reorder-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626420311-PkUiGI-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 240px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626420320-YUiulT-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 320px\" />"
    }
  ],
  "rotting-oranges": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/02/16/oranges.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 137px; width: 650px\" />"
    }
  ],
  "maximal-square": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/26/max1grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 319px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/26/max2grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 165px; height: 165px\" />"
    }
  ],
  "binary-tree-level-order-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/tree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 277px; height: 302px\" />"
    }
  ],
  "copy-list-with-random-pointer": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/01/09/e1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 142px; width: 700px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/01/09/e2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 114px; width: 700px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/01/09/e3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 122px; width: 700px\" />"
    }
  ],
  "binary-tree-inorder-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/15/inorder_1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 200px; width: 125px\" />"
    }
  ],
  "search-a-2d-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/05/mat.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 242px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/11/25/mat2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 242px\" />"
    }
  ],
  "maximum-depth-of-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/26/tmp-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 277px\" />"
    }
  ],
  "remove-nth-node-from-end-of-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/03/remove_ex1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 542px; height: 222px\" />"
    }
  ],
  "rotate-image": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/28/mat1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 188px; width: 500px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/28/mat2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 201px; width: 500px\" />"
    }
  ],
  "invert-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/14/invert1-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 165px; width: 500px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/14/invert2-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 120px\" />"
    }
  ],
  "set-matrix-zeroes": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/17/mat1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px; height: 169px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/17/mat2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px; height: 137px\" />"
    }
  ],
  "validate-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/01/tree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 302px; height: 182px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/01/tree2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 422px; height: 292px\" />"
    }
  ],
  "diameter-of-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/06/diamtree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 292px; height: 302px\" />"
    }
  ],
  "linked-list-cycle": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/07/circularlinkedlist.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/07/circularlinkedlist_test2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/07/circularlinkedlist_test3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "largest-rectangle-in-histogram": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/histogram.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/histogram-1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "remove-linked-list-elements": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/06/removelinked-list.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 142px\" />"
    }
  ],
  "reverse-linked-list-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/rev2ex2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 542px; height: 222px\" />"
    }
  ],
  "linked-list-cycle-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2018/12/07/circularlinkedlist.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/07/circularlinkedlist_test2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/07/circularlinkedlist_test3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "pascals-triangle": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626927345-DZmfxB-PascalTriangleAnimated2.gif\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "path-sum-iii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/09/pathsum3-1-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 452px\" />"
    }
  ],
  "maximal-rectangle": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1722912576-boIxpm-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 402px; height: 322px\" />"
    }
  ],
  "convert-sorted-array-to-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/18/btree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 302px; height: 222px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/18/btree2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 302px; height: 222px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/18/btree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 342px; height: 142px\" />"
    }
  ],
  "unique-paths": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1697422740-adxmsI-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 183px\" />"
    }
  ],
  "shu-de-zi-jie-gou-lcof": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1694684670-vwyIgY-two_tree.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1694685602-myWXCv-two_tree_2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "symmetric-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1698026966-JDYPDU-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 354px; height: 291px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1698027008-nPFLbM-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 308px; height: 258px\" />"
    }
  ],
  "word-search": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/04/word2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 242px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/04/word-1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 242px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/15/word3.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 242px\" />"
    }
  ],
  "longest-increasing-path-in-a-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/05/grid1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 242px; height: 242px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/27/tmp-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 253px; height: 253px\" />"
    }
  ],
  "integer-to-roman": [
    {
      "type": "table",
      "source": "leetcode-cn",
      "html": "<table>\n\t<thead>\n\t\t<tr>\n\t\t\t<th>符号</th>\n\t\t\t<th>值</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>I</td>\n\t\t\t<td>1</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>V</td>\n\t\t\t<td>5</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>X</td>\n\t\t\t<td>10</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>L</td>\n\t\t\t<td>50</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>C</td>\n\t\t\t<td>100</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>D</td>\n\t\t\t<td>500</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>M</td>\n\t\t\t<td>1000</td>\n\t\t</tr>\n\t</tbody>\n</table>"
    }
  ],
  "unique-paths-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/04/robot1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/04/robot2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "binary-tree-right-side-view": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/11/24/tmpd5jn43fs-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 207px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/11/24/tmpkpe40xeh-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 214px\" />"
    }
  ],
  "binary-tree-zigzag-level-order-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/tree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 277px; height: 302px\" />"
    }
  ],
  "valid-sudoku": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2021/04/12/250px-sudoku-by-l2g-20050714svg.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 250px; width: 250px\" />"
    }
  ],
  "remove-duplicates-from-sorted-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/list1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 160px; width: 200px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/list2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 123px; width: 300px\" />"
    }
  ],
  "partition-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/partition.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 662px; height: 222px\" />"
    }
  ],
  "house-robber-iii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/10/rob1-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/10/rob2-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "matchsticks-to-square": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/09/matchsticks1-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "rotate-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/rotate1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/roate2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 305px; height: 350px\" />"
    }
  ],
  "flatten-binary-tree-to-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/14/flaten.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 226px\" />"
    }
  ],
  "dungeon-game": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/13/dungeon-grid-1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 253px; height: 253px\" />"
    }
  ],
  "balanced-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/06/balance_1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 342px; height: 221px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/06/balance_2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 452px; height: 301px\" />"
    }
  ],
  "binary-tree-paths": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/12/paths-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 207px; height: 293px\" />"
    }
  ],
  "binary-tree-preorder-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/08/29/screenshot-2024-08-29-202743.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px; height: 264px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/08/29/tree_2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 350px; height: 286px\" />"
    }
  ],
  "path-sum": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/18/pathsum1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 356px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/18/pathsum2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "maximum-running-time-of-n-computers": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/01/06/example1-fit.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 762px; height: 150px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/01/06/example2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 629px; height: 150px\" />"
    }
  ],
  "maximum-width-of-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/05/03/width1-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 359px; height: 302px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/03/14/maximum-width-of-binary-tree-v3.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 442px; height: 422px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/05/03/width3-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 289px; height: 299px\" />"
    }
  ],
  "shortest-path-in-binary-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/18/example1_1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 234px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/18/example2_1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 216px; width: 500px\" />"
    }
  ],
  "remove-duplicates-from-sorted-list-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/linkedlist1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 142px; width: 500px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/linkedlist2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 164px; width: 400px\" />"
    }
  ],
  "odd-even-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/10/oddeven-linked-list.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 123px; width: 300px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/10/oddeven2-linked-list.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 142px; width: 500px\" />"
    }
  ],
  "game-of-life": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/26/grid1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/26/grid2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "root-equals-sum-of-children": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/04/08/graph3drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 281px; height: 199px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/04/08/graph3drawio-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 281px; height: 199px\" />"
    }
  ],
  "middle-of-the-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/23/lc-midlist1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 544px; height: 65px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/23/lc-midlist2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 664px; height: 65px\" />"
    }
  ],
  "same-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/20/ex1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 622px; height: 182px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/20/ex2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 382px; height: 182px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/20/ex3.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 622px; height: 182px\" />"
    }
  ],
  "serialize-and-deserialize-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/15/serdeser.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 442px; height: 324px\" />"
    }
  ],
  "sudoku-solver": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2021/04/12/250px-sudoku-by-l2g-20050714svg.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 250px; width: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2021/04/12/250px-sudoku-by-l2g-20050714_solutionsvg.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 250px; width: 250px\" />"
    }
  ],
  "delete-node-in-a-bst": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/04/del_node_1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 800px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/04/del_node_supp.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 350px\" />"
    }
  ],
  "ZL6zAn": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626667010-nSGPXz-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 452px\" />"
    }
  ],
  "get-biggest-three-rhombus-sums-in-a-grid": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/23/pc73-q4-desc-2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 385px; height: 385px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/23/pc73-q4-ex1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 360px; height: 361px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/23/pc73-q4-ex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 217px; height: 217px\" />"
    }
  ],
  "lowest-common-ancestor-of-a-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/12/14/binarysearchtree_improved.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 190px; width: 200px\" />"
    }
  ],
  "add-two-numbers-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626420025-fZfzMX-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 302px\" />"
    }
  ],
  "unique-binary-search-trees-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/18/uniquebstn3.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 600px; height: 148px\" />"
    }
  ],
  "path-sum-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/18/pathsumii1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 356px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/18/pathsum2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 212px; height: 181px\" />"
    }
  ],
  "sum-root-to-leaf-numbers": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/num1tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 212px; height: 182px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/num2tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 292px; height: 302px\" />"
    }
  ],
  "trapping-rain-water-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/08/trap1-3d.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/08/trap2-3d.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "diagonal-traverse": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/10/diag1-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 334px; height: 334px\" />"
    }
  ],
  "kth-smallest-element-in-a-bst": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/28/kthtree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 212px; height: 301px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/28/kthtree2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 382px; height: 302px\" />"
    }
  ],
  "image-overlap": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/09/overlap1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px; height: 231px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/09/overlap_step1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px; height: 105px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/09/overlap_step2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px; height: 231px\" />"
    }
  ],
  "maximum-sum-bst-in-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/03/07/sample_1_1709.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 250px; width: 320px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/03/07/sample_2_1709.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 180px; width: 134px\" />"
    }
  ],
  "count-number-of-trapezoids-i": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/05/01/desmos-graph-6.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/05/01/desmos-graph-7.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/05/01/desmos-graph-8.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/04/29/desmos-graph-5.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    }
  ],
  "average-of-levels-in-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/09/avg1-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/09/avg2-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "domino-and-tromino-tiling": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1770603172-yzJnnq-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 195px; width: 362px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1770603196-URXvsC-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 226px; width: 500px\" />"
    }
  ],
  "sum-of-left-leaves": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/04/08/leftsum-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "uncrossed-lines": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/04/26/142.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 286px\" />"
    }
  ],
  "interleaving-string": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/02/interleave.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "surrounded-regions": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1718167191-XNjUTG-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 367px; height: 158px\" />"
    }
  ],
  "max-sum-of-rectangle-no-larger-than-k": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/18/sum-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 255px; height: 176px\" />"
    }
  ],
  "the-skyline-problem": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/01/merged.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 331px; width: 800px\" />"
    }
  ],
  "maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/12/15/e1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 186px; width: 335px\" />"
    }
  ],
  "count-submatrices-with-top-left-element-and-sum-less-than-k": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/01/example1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/01/example21.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "trim-a-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/09/trim1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 126px; width: 450px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/09/trim2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 277px; width: 450px\" />"
    }
  ],
  "leaf-similar-trees": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/03/leaf-similar-1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 237px; width: 600px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/03/leaf-similar-2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 110px; width: 300px\" />"
    }
  ],
  "maximum-number-of-events-that-can-be-attended": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/02/16/e1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 267px; width: 400px\" />"
    }
  ],
  "number-of-provinces": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/24/graph1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 222px; height: 142px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/24/graph2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 222px; height: 142px\" />"
    }
  ],
  "sliding-puzzle": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/29/slide1-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/29/slide2-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/29/slide3-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "delete-nodes-and-return-forest": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/07/05/screen-shot-2019-07-01-at-53836-pm.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 150px; width: 237px\" />"
    }
  ],
  "count-sub-islands": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/10/test1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 493px; height: 205px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/03/testcasex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 491px; height: 201px\" />"
    }
  ],
  "all-ancestors-of-a-node-in-a-directed-acyclic-graph": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/12/12/e1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 322px; height: 265px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/12/12/e2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 343px; height: 299px\" />"
    }
  ],
  "range-sum-query-2d-immutable": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626332422-wUpUHT-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px\" />"
    }
  ],
  "binary-tree-level-order-traversal-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/tree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 277px; height: 302px\" />"
    }
  ],
  "minimum-falling-path-sum": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1729566253-aneDag-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 500px; width: 499px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1729566282-dtXwRd-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 365px; width: 164px\" />"
    }
  ],
  "populating-next-right-pointers-in-each-node": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/02/14/116_sample.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 171px; width: 500px\" />"
    }
  ],
  "insertion-sort-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1724130387-qxfMwx-Insertion-sort-example-300px.gif\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1724130414-QbPAjl-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1724130432-zoOvdI-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "word-search-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/07/search1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/07/search2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "find-largest-value-in-each-tree-row": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/21/largest_e1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 172px; width: 300px\" />"
    }
  ],
  "maximum-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/24/tree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/12/24/tree2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "exclusive-time-of-functions": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/04/05/diag1b.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 550px; height: 239px\" />"
    }
  ],
  "transpose-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/10/hint_transpose.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 600px; height: 197px\" />"
    }
  ],
  "n-ary-tree-level-order-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2018/10/12/narytreeexample.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 100%; max-width: 300px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/11/08/sample_4_964.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 296px; height: 241px\" />"
    }
  ],
  "maximum-profit-from-trading-stocks-with-discounts": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1748074339-Jgupjx-screenshot-2025-04-10-at-053641.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px; height: 66px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1748074339-BkQeTc-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 180px; height: 153px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1748074339-XmAKtD-screenshot-2025-04-10-at-054114.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px; height: 77px\" />"
    }
  ],
  "minimum-depth-of-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/12/ex_depth.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 432px; height: 302px\" />"
    }
  ],
  "count-complete-tree-nodes": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/14/complete.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 372px; height: 302px\" />"
    }
  ],
  "minimum-moves-to-move-a-box-to-their-target-location": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/11/16/sample_1_1620.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 335px; width: 500px\" />"
    }
  ],
  "cinema-seat-allocation": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/03/21/cinema_seats_1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 149px; width: 400px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/03/21/cinema_seats_3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 96px; width: 400px\" />"
    }
  ],
  "find-the-maximum-number-of-fruits-collected": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/08/07/clideo_editor_d0b446db9ba448e1a3fcdd0eecdb58d0-ezgifcom-crop.gif\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 210px\" />"
    }
  ],
  "unique-binary-search-trees": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/18/uniquebstn3.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 600px; height: 148px\" />"
    }
  ],
  "count-number-of-trapezoids-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/04/29/desmos-graph-4.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/04/29/desmos-graph-3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/04/29/desmos-graph-5.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px; height: 250px\" />"
    }
  ],
  "construct-binary-tree-from-inorder-and-postorder-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/19/tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "maximize-area-of-square-hole-in-grid": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/11/05/screenshot-from-2023-11-05-22-40-25.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 411px; height: 220px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/11/04/screenshot-from-2023-11-04-17-01-02.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 368px; height: 145px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/03/12/unsaved-image-2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 648px; height: 218px\" />"
    }
  ],
  "maximum-matrix-sum": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/16/pc79-q2ex1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 401px; height: 81px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/16/pc79-q2ex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 321px; height: 121px\" />"
    }
  ],
  "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/06/21/ex1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 262px; width: 259px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/06/21/msts.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 553px; width: 540px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/06/21/ex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 253px; width: 247px\" />"
    }
  ],
  "largest-submatrix-with-rearrangements": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2021/01/17/screenshot-2020-12-30-at-40536-pm.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px; height: 144px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2021/01/17/screenshot-2020-12-30-at-40852-pm.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 62px\" />"
    }
  ],
  "flatten-a-multilevel-doubly-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/11/09/flatten11.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 339px; width: 700px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/11/09/flatten12.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 69px; width: 1000px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/11/09/flatten2.1jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 200px; width: 200px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/11/24/list.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 87px; width: 300px\" />"
    }
  ],
  "delete-node-in-a-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/01/node1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 286px; width: 400px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/01/node2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 315px; width: 400px\" />"
    }
  ],
  "longest-absolute-file-path": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/28/mdir.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 142px; width: 300px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/28/dir1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 101px; width: 200px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/28/dir2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 151px; width: 300px\" />"
    }
  ],
  "01-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626667201-NCWmuP-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 150px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626667205-xFxIeK-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 150px\" />"
    }
  ],
  "knight-probability-in-chessboard": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/10/12/knight.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 300px; width: 300px\" />"
    }
  ],
  "special-positions-in-a-binary-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/12/23/special1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 244px; height: 245px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/12/24/special-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 244px; height: 245px\" />"
    }
  ],
  "separate-squares-i": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1739609465-UaFzhk-4062example1drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 378px; height: 352px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1739609527-TWqefZ-4062example2drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 378px; height: 352px\" />"
    }
  ],
  "minesweeper": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/08/09/untitled.jpeg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; max-width: 400px; height: 269px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/08/09/untitled-2.jpeg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; max-width: 400px; height: 275px\" />"
    }
  ],
  "add-one-row-to-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/15/addrow-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 231px; width: 500px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/11/add2-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 277px; width: 500px\" />"
    }
  ],
  "even-odd-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/10/04/sample_1_1966.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 229px; width: 362px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/10/04/sample_2_1966.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 167px; width: 363px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/10/04/sample_1_333_1966.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 167px; width: 363px\" />"
    }
  ],
  "k-radius-subarray-averages": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/11/07/eg1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 343px; height: 119px\" />"
    }
  ],
  "P5rCT8": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/01/23/285_example_1.PNG\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 117px; width: 122px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/01/23/285_example_2.PNG\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 229px; width: 246px\" />"
    }
  ],
  "er-cha-sou-suo-shu-de-hou-xu-bian-li-xu-lie-lcof": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1706665328-rfvWhs-%E6%88%AA%E5%B1%8F2024-01-31%2009.41.48.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px; height: 279px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1694762510-vVpTic-%E5%89%91%E6%8C%8733.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "xu-lie-hua-er-cha-shu-lcof": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/15/serdeser.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "convert-sorted-list-to-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/17/linked.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 388px; width: 500px\" />"
    }
  ],
  "find-mode-in-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/03/11/mode-tree.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 142px; height: 222px\" />"
    }
  ],
  "swim-in-rising-water": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/29/swim1-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/29/swim2-grid-1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "vertical-order-traversal-of-a-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/29/vtree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 431px; height: 304px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/29/vtree2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 512px; height: 304px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/29/vtree3.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 512px; height: 304px\" />"
    }
  ],
  "parallel-courses-iii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/07/ex1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 392px; height: 232px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/07/ex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 365px\" />"
    }
  ],
  "count-number-of-texts": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1722224025-gsUAIv-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px; height: 162px\" />"
    }
  ],
  "coin-bonus": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/09/09/coin_example_1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 344px; width: 300px\" />"
    }
  ],
  "you-le-yuan-de-mi-gong": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/595b60797d4a461287864a8cd05bba1d3b8760104ff83f43b902fd68477be9c3-Screenshot%202020-03-20%20at%2017.04.58.png\" alt=\"Screenshot 2020-03-20 at 17.04.58.png\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/c01c1efc423b916267c2a3a170266c925c368d62afa047c267cc1020970e55d9-%E5%9B%BE%E7%89%87.gif\" alt=\"图片.gif\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "sum-of-root-to-leaf-binary-numbers": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/04/04/sum-of-root-to-leaf-binary-numbers.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "reorder-routes-to-make-all-paths-lead-to-the-city-zero": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/05/30/sample_1_1819.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 150px; width: 240px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/05/30/sample_2_1819.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 60px; width: 380px\" />"
    }
  ],
  "find-if-path-exists-in-graph": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/08/14/validpath-ex1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 141px; height: 121px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/08/14/validpath-ex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 281px; height: 141px\" />"
    }
  ],
  "remove-nodes-from-linked-list": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/10/02/drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 631px; height: 51px\" />"
    }
  ],
  "reschedule-meetings-for-maximum-free-time-i": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/12/21/example0_rescheduled.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 375px; height: 123px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/12/21/example1_rescheduled.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 375px; height: 125px\" />"
    }
  ],
  "partition-list-lcci": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/04/partition.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 662px; height: 222px\" />"
    }
  ],
  "min-cost-to-connect-all-points": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/26/d.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 268px; width: 214px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/08/26/c.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 268px; width: 214px\" />"
    }
  ],
  "find-the-minimum-and-maximum-number-of-nodes-between-critical-points": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/13/a1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 148px; height: 55px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/13/a2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 624px; height: 46px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/14/a5.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 624px; height: 39px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/13/a4.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 345px; height: 52px\" />"
    }
  ],
  "flood-fill": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/06/01/flood1-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "maximum-level-sum-of-a-binary-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/08/17/capture.jpeg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 175px; width: 200px\" />"
    }
  ],
  "paths-in-matrix-whose-sum-is-divisible-by-k": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/08/13/image-20220813183124-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 437px; height: 200px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/08/17/image-20220817112930-3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 85px; width: 132px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/08/12/image-20220812224605-3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 257px; height: 200px\" />"
    }
  ],
  "climbing-stairs-ii": [
    {
      "type": "table",
      "source": "leetcode-cn",
      "html": "<table>\n\t<tbody>\n\t\t<tr>\n\t\t\t<th>跳跃</th>\n\t\t\t<th>成本计算</th>\n\t\t\t<th>成本</th>\n\t\t</tr>\n\t</tbody>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>0 → 1</td>\n\t\t\t<td><code>costs[0] + (1 - 0)<sup>2</sup> = 1 + 1</code></td>\n\t\t\t<td>2</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>1 → 2</td>\n\t\t\t<td><code>costs[1] + (2 - 1)<sup>2</sup> = 2 + 1</code></td>\n\t\t\t<td>3</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2 → 4</td>\n\t\t\t<td><code>costs[3] + (4 - 2)<sup>2</sup> = 4 + 4</code></td>\n\t\t\t<td>8</td>\n\t\t</tr>\n\t</tbody>\n</table>"
    },
    {
      "type": "table",
      "source": "leetcode-cn",
      "html": "<table>\n\t<tbody>\n\t\t<tr>\n\t\t\t<th>跳跃</th>\n\t\t\t<th>成本计算</th>\n\t\t\t<th>成本</th>\n\t\t</tr>\n\t</tbody>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>0 → 2</td>\n\t\t\t<td><code>costs[2] + (2 - 0)<sup>2</sup> = 1 + 4</code></td>\n\t\t\t<td>5</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>2 → 4</td>\n\t\t\t<td><code>costs[4] + (4 - 2)<sup>2</sup> = 2 + 4</code></td>\n\t\t\t<td>6</td>\n\t\t</tr>\n\t</tbody>\n</table>"
    }
  ],
  "er-cha-sou-suo-shu-yu-shuang-xiang-lian-biao-lcof": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2018/10/12/bstdllreturndll.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2018/10/12/bstdllreturnbst.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "binary-tree-postorder-traversal": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/08/29/screenshot-2024-08-29-202743.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px; height: 264px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/08/29/tree_2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 350px; height: 286px\" />"
    }
  ],
  "all-paths-from-source-to-target": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/28/all_1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/28/all_2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "search-in-a-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/12/tree1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 179px; width: 250px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/01/12/tree2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 179px; width: 250px\" />"
    }
  ],
  "maximum-score-from-grid-operations": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/05/11/one.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px; height: 200px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/05/11/two-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px; height: 200px\" />"
    }
  ],
  "alphabet-board-path": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2019/07/28/azboard.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px\" />"
    }
  ],
  "minimum-edge-reversals-so-every-node-is-reachable": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/08/26/image-20230826221104-3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/08/26/image-20230826225541-2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "sum-of-matrix-after-queries": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/05/11/exm1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 681px; height: 161px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/05/11/exm2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 681px; height: 331px\" />"
    }
  ],
  "kth-smallest-path-xor-sum": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/05/29/screenshot-2025-05-29-at-204434.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 149px; width: 160px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/05/29/screenshot-2025-05-29-at-204534.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 346px; height: 50px\" />"
    }
  ],
  "parallel-courses-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/06/27/leetcode_parallel_courses_1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 164px; width: 300px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/06/27/leetcode_parallel_courses_2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 234px; width: 300px\" />"
    }
  ],
  "partition-array-into-two-arrays-to-minimize-sum-difference": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/02/ex1.png\" alt=\"example-1\" loading=\"lazy\" decoding=\"async\" style=\"width: 240px; height: 106px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/10/02/ex3.png\" alt=\"example-3\" loading=\"lazy\" decoding=\"async\" style=\"width: 316px; height: 106px\" />"
    }
  ],
  "queens-that-can-attack-the-king": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1703052515-HqjAJq-chess1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 400px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1703052660-bPPflt-chess2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 400px\" />"
    }
  ],
  "detect-squares": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/09/01/image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 869px; height: 504px\" />"
    }
  ],
  "maximum-square-area-by-removing-fences-from-a-field": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/11/05/screenshot-from-2023-11-05-22-40-25.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/11/22/maxsquareareaexample1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 285px; height: 242px\" />"
    }
  ],
  "find-the-largest-area-of-square-inside-two-rectangles": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/05/example12.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 443px; height: 364px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/04/rectanglesexample2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 445px; height: 365px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/04/rectanglesexample3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 444px; height: 364px\" />"
    }
  ],
  "separate-squares-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1739609602-zhNmeC-4065example1drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 269px; height: 203px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1739609605-ezeVgk-4065example2drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 269px; height: 203px\" />"
    }
  ],
  "shortest-path-in-a-weighted-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1744423814-SDrlUl-screenshot-2025-03-13-at-133524.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 200px; height: 75px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1744423824-zZqYvM-screenshot-2025-03-13-at-132247.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 180px; height: 141px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1744423806-WSWbOq-screenshot-2025-03-13-at-133306.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 400px; height: 83px\" />"
    }
  ],
  "last-day-where-you-can-still-cross": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/27/1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 624px; height: 162px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/27/2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 504px; height: 178px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/07/27/3.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 666px; height: 167px\" />"
    }
  ],
  "maximum-number-of-k-divisible-components": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/08/07/example12-cropped2svg.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 1024px; height: 453px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2023/08/07/example21svg-1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 999px; height: 338px\" />"
    }
  ],
  "check-if-a-parentheses-string-can-be-valid": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/11/06/eg1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 311px; height: 101px\" />"
    }
  ],
  "maximum-sum-of-an-hourglass": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/08/21/img.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 243px; height: 243px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/08/21/1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 323px; height: 323px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/08/21/2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 243px; height: 243px\" />"
    }
  ],
  "number-of-submatrices-that-sum-to-target": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/09/02/mate1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 242px; height: 242px\" />"
    }
  ],
  "longest-cycle-in-a-graph": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/06/08/graph4drawio-5.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 335px; height: 191px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/06/07/graph4drawio-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 171px; height: 161px\" />"
    }
  ],
  "minimum-cost-walk-in-weighted-graph": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/31/q4_example1-1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 351px; height: 141px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2024/01/31/q4_example2e.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 211px; height: 181px\" />"
    }
  ],
  "minimum-time-to-reach-destination-in-directed-graph": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/06/05/screenshot-2025-06-06-at-004535.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 150px; height: 141px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/06/05/screenshot-2025-06-06-at-004757.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 170px; height: 219px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/06/05/screenshot-2025-06-06-at-004914.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 150px; height: 145px\" />"
    }
  ],
  "robot-in-a-grid-lcci": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2018/10/22/robot_maze.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 183px; width: 400px\" />"
    }
  ],
  "maximal-network-rank": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/10/11/ex1.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 292px; height: 172px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/10/11/ex2.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 292px; height: 172px\" />"
    }
  ],
  "number-of-flowers-in-full-bloom": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/03/02/ex1new.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 550px; height: 216px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2022/03/02/ex2new.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 450px; height: 195px\" />"
    }
  ],
  "minimum-cost-path-with-edge-reversals": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2025/05/07/e1drawio.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 171px; height: 111px\" />"
    }
  ],
  "pyramid-transition-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/08/26/pyramid1-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 232px; width: 600px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/08/26/pyramid2-grid.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 359px; width: 600px\" />"
    }
  ],
  "design-skiplist": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1702370216-mKQcTt-1506_skiplist.gif\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 500px; height: 173px\" />"
    }
  ],
  "minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/12/13/matrix.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" />"
    }
  ],
  "convert-bst-to-greater-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2019/05/03/tree.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 364px; width: 534px\" />"
    }
  ],
  "merge-two-binary-trees": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2021/02/05/merge.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 163px; width: 600px\" />"
    }
  ],
  "n-queens-ii": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/11/13/queens.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 600px; height: 268px\" />"
    }
  ],
  "recover-binary-search-tree": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/28/recover1.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 300px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.com/uploads/2020/10/28/recover2.jpg\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 208px; width: 400px\" />"
    }
  ],
  "redundant-connection": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626676174-hOEVUL-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 152px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626676179-kGxcmu-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 250px\" />"
    }
  ],
  "number-of-operations-to-make-network-connected": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/01/11/sample_1_1677.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 167px; width: 570px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://assets.leetcode.cn/aliyun-lc-upload/uploads/2020/01/11/sample_2_1677.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"height: 175px; width: 660px\" />"
    }
  ],
  "LGjMqU": [
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626420311-PkUiGI-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 240px\" />"
    },
    {
      "type": "image",
      "source": "leetcode-cn",
      "html": "<img src=\"https://pic.leetcode.cn/1626420320-YUiulT-image.png\" alt=\"\" loading=\"lazy\" decoding=\"async\" style=\"width: 320px\" />"
    }
  ]
} satisfies Record<string, LeetcodeProblemStatementAsset[]>;

export const leetcodeProblemStatementAssetStats = {
  "problems": 872,
  "withAssets": 202,
  "images": 353,
  "tables": 3,
  "failed": 0
};
